-- 1. 지역별 부서의 수를 조회한다. (부서가 없으면 부서의 수는 0으로 조회한다.) - 23
SELECT
	L.LOCATION_ID,
	COUNT(D.DEPARTMENT_ID)
FROM
	LOCATIONS L
LEFT JOIN DEPARTMENTS D
    ON
	L.LOCATION_ID = D.LOCATION_ID
GROUP BY
	L.LOCATION_ID
;

-- 2. 지역별 사원의 평균월급을 조회한다. (사원이 없으면 평균월급은 0으로 조회한다.) - 23
SELECT
	L.LOCATION_ID,
	NVL(AVG(E.SALARY), 0) AS AVG_SALARY
FROM
	LOCATIONS L
LEFT JOIN DEPARTMENTS D
    ON
	L.LOCATION_ID = D.LOCATION_ID
LEFT JOIN EMPLOYEES E
    ON
	D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY
	L.LOCATION_ID
;

-- 3. 도시명 별 사원의 수를 도시명으로 오름차순 정렬하여 조회한다.(사원이 없으면 사원의 수는 0으로 조회한다.) - 23
SELECT
	L.CITY,
	COUNT(E.EMPLOYEE_ID)
FROM
	LOCATIONS L
LEFT JOIN DEPARTMENTS D
    ON
	L.LOCATION_ID = D.LOCATION_ID
LEFT OUTER JOIN EMPLOYEES E
ON
	D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY
	L.CITY
ORDER BY
	L.CITY ASC
;

-- 4. 모든 사원들의 현재 직무명과 과거의 직무명을 조회한다. 만약 직무가 한번도 변경되지 않았다면, 과거의 직무명은 '없음' 으로 조회한다. - 110
SELECT
	E.EMPLOYEE_ID,
	E.FIRST_NAME,
	J_CUR.JOB_TITLE AS CURRENT_JOB,
	NVL(J_HIS.JOB_TITLE, '없음') AS PREVIOUS_JOB
FROM
	EMPLOYEES E
INNER JOIN JOBS J_CUR
	ON
	E.JOB_ID = J_CUR.JOB_ID
LEFT OUTER JOIN JOB_HISTORY JH
	ON
	E.EMPLOYEE_ID = JH.EMPLOYEE_ID
LEFT OUTER JOIN JOBS J_HIS
    ON
	JH.JOB_ID = J_HIS.JOB_ID
ORDER BY
	E.EMPLOYEE_ID
;


