--SELECT * FROM EMPLOYEES;
--SELECT SYSDATE FROM DUAL;
--select COLUMN ....
--	FROM TABLE..
--;

-- JOIN 문제 언습
-- 사원의 이름과 성, 근무중인 부서 번호화 부서명을 조회한다.
-- EQUIP JOIN
SELECT
	E.FIRST_NAME,
	E.LAST_NAME,
	D.DEPARTMENT_ID,
	D.DEPARTMENT_NAME
FROM
	EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
;

-- 사원의 이름과 성, 월급, 수행중이 직무의 아이디, 직무의 이름, 직무별 최대 월급을 조회한다.
SELECT
	E.FIRST_NAME,
	E.LAST_NAME,
	E.SALARY,
	J.JOB_ID,
	J.JOB_TITLE,
	J.MAX_SALARY
FROM
	EMPLOYEES E
INNER JOIN JOBS J
ON
	E.JOB_ID = J.JOB_ID
;

-- 사원의 이름, 사원번호, 월급, 수행중인 직무의 이름, 근무중인 부서의 이름을 조회한다.
SELECT
	E.EMPLOYEE_ID,
	E.FIRST_NAME,
	E.SALARY,
	J.JOB_TITLE,
	D.DEPARTMENT_NAME
FROM
	EMPLOYEES E
INNER JOIN JOBS J
ON
	E.JOB_ID = J.JOB_ID
INNER JOIN DEPARTMENTS D 
ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
	
;

-- 사원의 사원 번호, 이름, 성, 이메일과 근무중인 도시의 이름을 조회한다.
SELECT 
	E.EMPLOYEE_ID,
	E.FIRST_NAME,
	E.LAST_NAME,
	E.EMAIL,
	L.CITY
FROM
	EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN LOCATIONS L
ON
	D.LOCATION_ID = L.LOCATION_ID
;

-- 모든 사원들의 이름, 상사의 사원번호, 상사의 사원명을 조회한다.
SELECT
	E.FIRST_NAME,
	M.EMPLOYEE_ID,
	M.FIRST_NAME
FROM
	EMPLOYEES E
INNER JOIN EMPLOYEES M
ON
	E.MANAGER_ID = M.EMPLOYEE_ID
;

-- 모든 사원들의 이름, 상사의 사원번호, 상사의 사원명, 사원이 수행중인 직무의 이름, 상사가 수행중인 직무의 이름을 조회한다.
SELECT
	E.FIRST_NAME,
	M.EMPLOYEE_ID,
	M.FIRST_NAME,
	E_J.JOB_TITLE,
	M_J.JOB_TITLE
FROM
	EMPLOYEES E
INNER JOIN EMPLOYEES M
ON
	M.EMPLOYEE_ID = E.MANAGER_ID
INNER JOIN JOBS E_J
ON
	E.JOB_ID = E_J.JOB_ID
INNER JOIN JOBS M_J
ON
	M.JOB_ID = M_J.JOB_ID
;

-- JOIN 으로 GROUP BY 실습
-- 목적 조인 + 그룹핑 사용하는 경우
-- 주문 목록(상품준비중 : 3, 배송시작 : 4, 배송중 : 5, 배송완료 : 0, 리뷰작성 : 14, 리뷰작성가능 : 3 등등 만들때 쓴다.)

--  직무명 별 수행중인 사원의 수를 조회한다.
-- STEP 1. 직무 아이디별 수행중인 사원의 수를 조회
SELECT
	JOB_ID,
	COUNT(EMPLOYEE_ID)
FROM
	EMPLOYEES
GROUP BY
	JOB_ID
;

-- STEP 2. 직무명 별 수행중인 사원의 수를 조회
SELECT
	J.JOB_TITLE,
	COUNT(E.EMPLOYEE_ID)
FROM
	EMPLOYEES E
INNER JOIN JOBS J
	ON
	E.JOB_ID = J.JOB_ID
GROUP BY
	J.JOB_TITLE
;

-- 도시별 근무중인 사원의 수를 조회한다.
SELECT
	L.CITY,
	COUNT(E.EMPLOYEE_ID)
FROM
	EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN LOCATIONS L
ON
	L.LOCATION_ID = D.LOCATION_ID
GROUP BY
	L.CITY
;

--도시별, 부서별로 군무중인 사원의 수를 조회한다.
SELECT
	L.CITY,
	D.DEPARTMENT_NAME,
	COUNT(E.EMPLOYEE_ID)
FROM
	EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN LOCATIONS L
ON
	L.LOCATION_ID = D.LOCATION_ID
GROUP BY
	L.CITY,
	D.DEPARTMENT_NAME
;

-- 재귀 조인
-- 최 상위 직원의 모든 부하직원들의 사원번호, 이름, 상사사원번호를 계단식(계층식)으로 조회한다.
SELECT
	LEVEL,
	-- 몇 차수인지를 보여주는게 레벨이다
	EMPLOYEE_ID,
	FIRST_NAME,
	MANAGER_ID
FROM
	EMPLOYEES
START WITH
	MANAGER_ID IS NULL
	-- root node 지정
CONNECT BY
	PRIOR EMPLOYEE_ID = MANAGER_ID
	-- 상하관게를 명시(상위 노드 기준으로 작성 : 상사의 사원 번호는 부하직원의 상사번화화 같다.)
	-- 상하관계를 찹아주는 것 
	-- 다른 
;

-- 101번 사원의 모든 부하직원들의 사원번호, 이름, 상사사원본호를 계츨식으로 조회한다.
SELECT
	LEVEL,
	EMPLOYEE_ID,
	FIRST_NAME,
	MANAGER_ID
FROM
	EMPLOYEES
START WITH
	EMPLOYEE_ID = 101
	-- root node 지정.
CONNECT BY
	PRIOR EMPLOYEE_ID = MANAGER_ID
;

-- 206번 사원의 모든 상사 직원들의 사원번호, 이름, 상사사원번호를 계층식으로 조회한다.
SELECT
	LEVEL,
	EMPLOYEE_ID,
	FIRST_NAME,
	MANAGER_ID
FROM
	EMPLOYEES
START WITH
	EMPLOYEE_ID = 206
	-- root node 지정.
CONNECT BY
	PRIOR MANAGER_ID = EMPLOYEE_ID
	-- 상하관게를 명시(상위 노드 기준으로 작성 : 부하직원의 상사 사원 번호는 상사직원의 사원 번호다.)
ORDER BY LEVEL DESC
;

-- 페이징(PAGINATION) 이랑 FETCH FIRST
-- 가장 많은우러급을 받는 사원 한 명만 조회한다.
-- ROWNUM : 순위를 뽑고 싶을때 사용
SELECT
	*
FROM
	EMPLOYEES
WHERE
	SALARY = (
	SELECT
		MAX(SALARY)
	FROM
		EMPLOYEES)
;

-- SCALA PUERY
-- Select의 결과를 fetch 할떄마다 서브쿼리를 실행 ==> 실행된 단 하나의 ROW & COLUMN을 Fetch 하는 방법.
-- 사용 권하지 않음 --> 성능 하락의 주요 원인.
-- => 300개를 Fetch 하면 Scala 쿼리가 3000번 수행됨
-- 사용을 해야할 때 - 어쩔 수 없는 상황일 때
-- 어떤 데이터 하나를 조회하기 위해 하나 이상의 Join이 더 필요할 때, 기존의 조인 테이블의 수 == 7개 ==> 추가 정보를 얻어오기 위해 1개의 조인을 더 필요로 할 때
--	=> 추가된 테이블이 기존의 조인과는 큰 관계가 없을 때 사용
-- 부서명과 도시명을 조회한다, - 조인 X
SELECT
	D.DEPARTMENT_NAME,
	D.LOCATION_ID,
	(
	SELECT
		CITY
		-- SCALA 쿼리는 반드시 하나의 컬럼만 조회해야 한다. & 반드시 하나의 ROW만 조회되어야 한다.
	FROM
		LOCATIONS L
	WHERE
		L.LOCATION_ID = D.LOCATION_ID)AS CITY,
	'도시의 이름은 ' || (SELECT CITY
					FROM LOCATIONS L
					WHERE L.LOCATION_ID = D.LOCATION_ID) || '입니다.'
FROM
	DEPARTMENTS D
;

-- 도시명과 부서의 이름을 조회한다. 조인 X
-- ERROR:ORA-01427: 단일 행 하위 질의에 2개 이상의 행이 리턴되었습니다. 라고 나온다.
SELECT
	L.CITY,
	L.LOCATION_ID,
	(
	SELECT
		DEPARTMENT_NAME
	FROM
		DEPARTMENTS D
	WHERE
		D.LOCATION_ID = L.LOCATION_ID) AS DEPT_NAME
FROM
	LOCATIONS L
;

-- 글자 채우기(LPAD(), RPAD())
--LPAD(컬럼, 자리수, 남은 자리수 만큼 채울 문자) --> LEFT PADDING 컬럼의 값 왼쪽에 자리수만큼 채움.
-- RPAD(컬럼, 자리수, 남은 자리수 만큼 채울 문자) --> RIGHT PADDING 컬럼의 값 오른쪽에 자리수만큼 채움.
WITH TMEP AS (
SELECT
	'YS' AS FIRST_NAME,
	'J' AS LAST_NAME
FROM
	DUAL)
SELECT
	FIRST_NAME,
	LAST_NAME,
	LPAD(FIRST_NAME, 5, '_'),
	LPAD(FIRST_NAME, 4, '_'),
	LPAD(FIRST_NAME, 3, '_'),
	LPAD(FIRST_NAME, 2, '_'),
	LPAD(FIRST_NAME, 1, '_')
FROM
	TMEP
;
-- 대소문자 바꾸기(UPPER(), LOWER())
-- UOOER(컬럼) --> 소문자들을 모두 대문자로 변경
-- LOWER(컬럼) --> 대문자들을 소문자로 변경
WITH TMEP2 AS (
SELECT
	'YS' AS FIRST_NAME,
	'J' AS LAST_NAME,
	'mcj' AS EMAIL
FROM
	DUAL)
SELECT
	FIRST_NAME,
	LAST_NAME,
	EMAIL,
	UPPER(EMAIL),
	LOWER(FIRST_NAME),
	LOWER(LAST_NAME)
FROM
	TMEP2
;
-- 문자열 연결 ( || <-- CONCAT)
-- EX> 'A' || 'B' ==> 'AB'
-- 문자열 바꾸기 함수 (REPLACE())
-- EX> 'MIN CHANG' ==> 'MIN_CHANG' REPLACE('MIN CHANG',' ', '_')
-- EX> 'MIN CHANG' ==> 'MINCHANG' REPLACE('MIN CHANG',' ', ) - 공백을 제거해라
WITH TMEP3 AS (
SELECT
	'Yeong seo' AS FIRST_NAME,
	'Jang' AS LAST_NAME,
	'MINCHANGJANG' AS EMAIL
FROM
	DUAL)
SELECT
	FIRST_NAME,
	LAST_NAME,
	FIRST_NAME || LAST_NAME,
	REPLACE(FIRST_NAME, ' ') || LAST_NAME
FROM
	TMEP3
;
-- 1. 현재 시간을 조회한다.
-- ORACLE 전용 시간(ANSI X)
SELECT
	SYSDATE
	-- 예약어 (현재 시간을 가리키는 ORACLE 전용 예약어)
FROM
	DUAL
;
-- 오늘 기준으로 하루 전의 날짜와 시간 조회
SELECT
	SYSDATE -1
FROM
	DUAL
;
-- 현재 시간을 기준으로 3시간 전의 날짜와 시간 조회
SELECT
	SYSDATE - 3 / 24
FROM
	DUAL
;
-- 현재 시간을 기준으로 15분 전의 날짜와 시간 조회
SELECT
	SYSDATE - 15 / 24 / 60
FROM
	DUAL
;
-- 현재 시간을 기준으로 50초 이후의 날짜와 시간 조회
-- 50초 / 24시간 / 60분 / 60초
SELECT
	SYSDATE + 50 / 24 / 60 / 60
	,
	SYSDATE
FROM
	DUAL
;
-- 1년을 더하던 빼던 12개우러을 써서 하면 됨.
SELECT
	ADD_MONTHS(SYSDATE, -2)
FROM
	DUAL
;
-- 2. 현재 시간을 "연-월-일" 포멧으로 조회한다.
-- TO_CHAR, TO_DATE를 가장 많이 사용
SELECT
	TO_CHAR(SYSDATE, 'YYYY-MM-DD'),
	TO_CHAR(SYSDATE, 'YYYY'),
	-- 연
	TO_CHAR(SYSDATE, 'MM'),
	-- 월
	TO_CHAR(SYSDATE, 'DD'),
	-- 일
	TO_CHAR(SYSDATE, 'HH'),
	-- 12시간 기준의 시
	TO_CHAR(SYSDATE, 'HH24'),
	-- 24시간 기준의 시
	TO_CHAR(SYSDATE, 'MI'),
	-- 분
	TO_CHAR(SYSDATE, 'SS')
	-- 초
FROM
	DUAL
;
-- 3. 한 시간 전 시간을 "시:분:초" 포멧으로 조회한다.
SELECT
	TO_CHAR(SYSDATE -1 / 24, 'HH24:MI:SS')
FROM
	DUAL
;
-- 2월 12일 연습문제
-- '2026-02-12' 텍스트를 날짜타입으로 변경한다.
-- '2026-02-12','YYYY-MM-DD' => 똑같은 형태로 작성해야 에러가 안남
-- 지금 최신버전은 텍스트의 길이만 맞으면 에러가 안남.
SELECT
	TO_DATE('2026-02-12', 'YYYY-MM-DD')
FROM
	DUAL
	-- 테이블이 없어서 사용
;
-- '2026-02-12' 기준으로 50일 이후 날짜와 시간을 조회한다.
SELECT
	TO_DATE('2026-02-12', 'YYYY-MM-DD') + 50
FROM
	DUAL
	-- 테이블이 없어서 사용
;
-- '2026-02-13' 기준으로 3시간 이후의 날짜와 시간을 조회한다.
SELECT
	TO_DATE('2026-02-13', 'YYYY-MM-DD') + 3 / 24
FROM
	DUAL
	-- 테이블이 없어서 사용
;
-- '2026-02-12' 기준으로 1일 후의 날짜만 조회한다.
SELECT
	TO_CHAR(TO_DATE('2026-02-12', 'YYYY-MM-DD') + 1, 'YYYY-MM-DD')
	-- 연월일만 가져와라
FROM
	DUAL
	-- 테이블이 없어서 사용
;
-- '2026-02-12' 기준으로 3일 후의 날짜와 시만을 조회한다.
SELECT
	TO_CHAR(TO_DATE('2026-02-12', 'YYYY-MM-DD') + 3, 'YYYY-MM-DD HH24')
FROM
	DUAL
	-- 테이블이 없어서 사용
;

-- 최고 월급을 받는 사원들의 사원 번호와 월급을 조회한다.
-- 1. 모르는 것? ==> 최고 월급
-- 2. 최고월급 -- 사원 월급
SELECT
	EMPLOYEE_ID,
	SALARY
FROM
	EMPLOYEES
WHERE
	SALARY = (
	SELECT
		MAX(SALARY)
	FROM
		EMPLOYEES)
;

-- 평균 월급보다 적게 받는 사원들의 사원번호와 월급을 조회한다.
SELECT
	EMPLOYEE_ID,
	SALARY
FROM
	EMPLOYEES
WHERE
	SALARY < (
	SELECT
		AVG(SALARY)
	FROM
		EMPLOYEES)
;


-- 수행하는 직무의 이름이 'Finance Manager'인 사원의 사원 번호와 직무 아이디를 조회한다.
SELECT
	EMPLOYEE_ID,
	JOB_ID
FROM
	EMPLOYEES
WHERE
	JOB_ID IN (
	SELECT
		JOB_ID
	FROM
		JOBS
	WHERE
		JOB_TITLE = 'Finance Manager')
;

-- Seattle에서 근무중인 사원의 이름, 성, 부서 번호를 조회한다.
SELECT
	E.FIRST_NAME,
	E.LAST_NAME,
	D.DEPARTMENT_ID
FROM
	EMPLOYEES E
INNER JOIN DEPARTMENTS D ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN LOCATIONS L ON
	D.LOCATION_ID = L.LOCATION_ID
WHERE
	L.CITY = 'Seattle'
;

SELECT
	FIRST_NAME,
	LAST_NAME,
	DEPARTMENT_ID
FROM
	EMPLOYEES
WHERE
	DEPARTMENT_ID IN`` (
	SELECT
		DEPARTMENT_ID
	FROM
		DEPARTMENTS
	WHERE
		LOCATION_ID = (
		SELECT
			LOCATION_ID
		FROM
			LOCATIONS
		WHERE
			CITY = 'Seattle'))
;

-- 중복 제거 문제
-- 모든 사원들의 상사 사원번호를 조회한다. 중복없이 - DISTINCT : 한줄이 중복되지 않게 하는것이다. 위에 있어야한다 SELECT 옆에
SELECT
	DISTINCT MANAGER_ID
FROM
	EMPLOYEES
;

-- 4. EMPLOYEES 테이블의 모든 정보를 조회한다.
-- *은 실무에서 사용하지 않는다
-- 1. 영향도 검사
-- 2. 사용 x, 컬럼 조사
-- 3. 분석용이
-- 를 위해 사용하지 않기
SELECT
	*
FROM
	EMPLOYEES
;

-- 5. DEPARTMENTS 테이블의 모든 정보를 조회한다.
SELECT
	DEPARTMENT_ID,
	DEPARTMENT_NAME,
	MANAGER_ID,
	LOCATION_ID
FROM
	DEPARTMENTS
;

-- 6. JOBS 테이블의 모든 정보를 조회한다.
SELECT
	JOB_ID,
	JOB_TITLE,
	MIN_SALARY,
	MAX_SALARY
FROM
	jobs
;

-- 7. LOCATIONS 테이블의 모든 정보를 조회한다.
SELECT
	LOCATION_ID,
	STREET_ADDRESS,
	POSTAL_CODE,
	CITY,
	STATE_PROVINCE,
	COUNTRY_ID
FROM
	LOCATIONS
;

-- 8. COUNTRIES 테이블의 모든 정보를 조회한다.
SELECT
	COUNTRY_ID,
	COUNTRY_NAME,
	REGION_ID
FROM
	COUNTRIES
;

-- 9. REGIONS 테이블의 모든 정보를 조회한다.
SELECT
	REGION_ID,
	REGION_NAME
FROM
	REGIONS
;

-- 10. JOB_HISTORY 테이블의 모든 정보를 조회한다.
SELECT
	DEPARTMENT_ID,
	START_DATE,
	END_DATE,
	JOB_ID,
	DEPARTMENT_ID
FROM
	JOB_HISTORY
;

-- 11. 90번 부서에서 근무하는 사원(EMPLOYEES)들의 모든 정보를 조회한다.
SELECT
	EMPLOYEE_ID,
	FIRST_NAME,
	LAST_NAME,
	EMAIL,
	PHONE_NUMBER,
	HIRE_DATE,
	JOB_ID,
	SALARY,
	COMMISSION_PCT,
	MANAGER_ID,
	DEPARTMENT_ID
FROM
	EMPLOYEES
WHERE
	DEPARTMENT_ID = 90
;

-- WHERE 90 = DEPARTMENT_ID; => 이렇게 작성할 경우 결과의 도출할때 까지의 시간이 완전히 달라서 이렇게 작성 x
-- 12. 90번 또는 100번 부서에서 근무하는 사원들의 모든 정보를 조회한다.
SELECT                 
	EMPLOYEE_ID,       
	FIRST_NAME,        
	LAST_NAME,         
	EMAIL,             
	PHONE_NUMBER,      
	HIRE_DATE,         
	JOB_ID,            
	SALARY,            
	COMMISSION_PCT,    
	MANAGER_ID,        
	DEPARTMENT_ID
FROM                   
	EMPLOYEES
WHERE                  
	DEPARTMENT_ID = 90
	OR DEPARTMENT_ID = 100
;

-- 13. 100번(MANAGER_ID) 상사의 직속 부하직원(DEPARTMENT_ID)의 모든 정보를 조회한다.
SELECT                 
	EMPLOYEE_ID,       
	FIRST_NAME,        
	LAST_NAME,         
	EMAIL,             
	PHONE_NUMBER,      
	HIRE_DATE,         
	JOB_ID,            
	SALARY,            
	COMMISSION_PCT,    
	MANAGER_ID,        
	DEPARTMENT_ID
FROM                   
	EMPLOYEES
WHERE
	MANAGER_ID = 100
;

-- 14. 직무 아이디가 AD_VP 인 사원의 모든 정보를 조회한다.
-- ORACLE, MYSQL, MARIADB, ...ALTER COLUMN TYPE => 날짜 = '0226-02-11', 숫자 = 10000, 텍스트 = 'AD_VP'
SELECT                 
	EMPLOYEE_ID,       
	FIRST_NAME,        
	LAST_NAME,         
	EMAIL,             
	PHONE_NUMBER,      
	HIRE_DATE,         
	JOB_ID,            
	SALARY,            
	COMMISSION_PCT,    
	MANAGER_ID,        
	DEPARTMENT_ID
FROM                   
	EMPLOYEES
WHERE
	JOB_ID = 'AD_VP'
;

-- 15. 월급이 7000 이상인 사원의 모든 정보를 조회한다.
SELECT                 
	EMPLOYEE_ID,       
	FIRST_NAME,        
	LAST_NAME,         
	EMAIL,             
	PHONE_NUMBER,      
	HIRE_DATE,         
	JOB_ID,            
	SALARY,            
	COMMISSION_PCT,    
	MANAGER_ID,        
	DEPARTMENT_ID
FROM                   
	EMPLOYEES
WHERE
	SALARY >= 7000
;

-- 16. 2005년 09월에 입사한 사원들의 모든 정보를 조회한다.
-- HIRE_DATE는 DATE 타입인데 ORACLE이 QUERY OPTIMZER를 가지고 있어
-- HIRE_DATE >= '2005-09-01' AND HIRE_DATE < '2005-10-01' 이렇게 작성해도 나오기는하다.
-- 하지만 타입을 일치시키는게 큰 탐색 비용이 들지 않아 빠르고 안전하게 결과를 도출할 수 있다.
SELECT                 
	EMPLOYEE_ID,       
	FIRST_NAME,        
	LAST_NAME,         
	EMAIL,             
	PHONE_NUMBER,      
	HIRE_DATE,         
	JOB_ID,            
	SALARY,            
	COMMISSION_PCT,    
	MANAGER_ID,        
	DEPARTMENT_ID
FROM                   
	EMPLOYEES
WHERE
	-- HIRE_DATE >= '2005-09-01' AND HIRE_DATE < '2005-10-01'
	-- 지금 처럼 큰지 작은지를 확인할려면 BETWEEN을 사용하는 것이 좋다.
	--	HIRE_DATE >= TO_DATE('2005-09-01', 'YYYY-MM-DD')
	--	AND HIRE_DATE < TO_DATE('2005-10-01', 'YYYY-MM-DD')
	HIRE_DATE BETWEEN TO_DATE('2005-09-01', 'YYYY-MM-DD') AND TO_DATE('2005-10-01', 'YYYY-MM-DD')-1
	-- 10월 1일 입사한 사람이 있을 수 있어서 9월 한달이라 -1을 해준다.
;

-- 17. 111번 사원의 모든 정보를 조회한다.
SELECT                 
	EMPLOYEE_ID,       
	FIRST_NAME,        
	LAST_NAME,         
	EMAIL,             
	PHONE_NUMBER,      
	HIRE_DATE,         
	JOB_ID,            
	SALARY,            
	COMMISSION_PCT,    
	MANAGER_ID,        
	DEPARTMENT_ID
FROM                   
	EMPLOYEES
WHERE
	EMPLOYEE_ID = 111
;

-- 18. 인센티브를 안받는 사원들의 모든 정보를 조회한다.
-- IS NOT NULL이나 IS NULL은 TYPE옆에 있는 NOT NULL이나 NULL 인지를 확인하고 사용해야한다.
-- NULL일 경우 사용가능
SELECT                 
	EMPLOYEE_ID,       
	FIRST_NAME,        
	LAST_NAME,         
	EMAIL,             
	PHONE_NUMBER,      
	HIRE_DATE,         
	JOB_ID,            
	SALARY,            
	COMMISSION_PCT,    
	MANAGER_ID,        
	DEPARTMENT_ID
FROM                   
	EMPLOYEES
WHERE
	COMMISSION_PCT IS NULL
;

-- 19. 인센티브를 받는 사원들의 모든 정보를 조회한다.
SELECT                 
	EMPLOYEE_ID,       
	FIRST_NAME,        
	LAST_NAME,         
	EMAIL,             
	PHONE_NUMBER,      
	HIRE_DATE,         
	JOB_ID,            
	SALARY,            
	COMMISSION_PCT,    
	MANAGER_ID,        
	DEPARTMENT_ID
FROM                   
	EMPLOYEES
WHERE
	COMMISSION_PCT IS NOT NULL
;

-- 20. 이름의 첫 글자가 'D' 인 사원들의 모든 정보를 조회한다.
SELECT                 
	EMPLOYEE_ID,       
	FIRST_NAME,        
	LAST_NAME,         
	EMAIL,             
	PHONE_NUMBER,      
	HIRE_DATE,         
	JOB_ID,            
	SALARY,            
	COMMISSION_PCT,    
	MANAGER_ID,        
	DEPARTMENT_ID
FROM                   
	EMPLOYEES
WHERE
	FIRST_NAME LIKE 'D%'
;

-- 21. 성의 마지막 글자가 'a' 인 사원들의 모든 정보를 조회한다.
SELECT                 
	EMPLOYEE_ID,       
	FIRST_NAME,        
	LAST_NAME,         
	EMAIL,             
	PHONE_NUMBER,      
	HIRE_DATE,         
	JOB_ID,            
	SALARY,            
	COMMISSION_PCT,    
	MANAGER_ID,        
	DEPARTMENT_ID
FROM                   
	EMPLOYEES
WHERE
	LAST_NAME NOT LIKE '%a'
;

-- 22. 전화번호에 '.124.'이 포함된 사원들의 모든 정보를 조회한다.
SELECT                 
	EMPLOYEE_ID,       
	FIRST_NAME,        
	LAST_NAME,         
	EMAIL,             
	PHONE_NUMBER,      
	HIRE_DATE,         
	JOB_ID,            
	SALARY,            
	COMMISSION_PCT,    
	MANAGER_ID,        
	DEPARTMENT_ID
FROM                   
	EMPLOYEES
WHERE
	PHONE_NUMBER LIKE '%.124.%'
;

-- 23. 직무 아이디가 'PU_CLERK'인 사원 중 월급이 3000 이상인 사원들의 모든 정보를 조회한다.
SELECT                 
	EMPLOYEE_ID,       
	FIRST_NAME,        
	LAST_NAME,         
	EMAIL,             
	PHONE_NUMBER,      
	HIRE_DATE,         
	JOB_ID,            
	SALARY,            
	COMMISSION_PCT,    
	MANAGER_ID,        
	DEPARTMENT_ID
FROM                   
	EMPLOYEES
WHERE
	JOB_ID = 'PU_CLERK'
	AND SALARY >= 3000
;

-- 24. 평균 월급보다 많이 받는 사원들의 사원번호, 이름, 성, 월급을 조회한다.
SELECT                 
	EMPLOYEE_ID,       
	FIRST_NAME,        
	LAST_NAME,                     
	SALARY
FROM                   
	EMPLOYEES
WHERE
	SALARY > (
	SELECT
		AVG(SALARY)
	FROM
		EMPLOYEES)
;

-- 25. 평균 월급보다 적게 받는 사원들의 사원번호, 월급, 부서번호를 조회한다.
SELECT
	EMPLOYEE_ID,
	SALARY,
	DEPARTMENT_ID
FROM
	EMPLOYEES
WHERE
	SALARY < (
	SELECT
		AVG(SALARY)
	FROM
		EMPLOYEES)
;

-- 26. 가장 많은 월급을 받는 사원의 사원번호, 이름, 월급을 조회한다.
SELECT
	EMPLOYEE_ID,
	FIRST_NAME,
	SALARY
FROM
	EMPLOYEES
WHERE
	SALARY >= (
	SELECT
		MAX(SALARY)
	FROM
		EMPLOYEES)
;

-- 27. 이름이 4글자인 사원의 모든 정보를 조회한다.
SELECT                 
	EMPLOYEE_ID,       
	FIRST_NAME,        
	LAST_NAME,         
	EMAIL,             
	PHONE_NUMBER,      
	HIRE_DATE,         
	JOB_ID,            
	SALARY,            
	COMMISSION_PCT,    
	MANAGER_ID,        
	DEPARTMENT_ID
FROM                   
	EMPLOYEES
WHERE
	FIRST_NAME LIKE '____'
	-- 숫자는 "_" 언더바 1개면 숫자 1개이다.
;

-- 이름이 4글자 이상
SELECT                 
	EMPLOYEE_ID,       
	FIRST_NAME,        
	LAST_NAME,         
	EMAIL,             
	PHONE_NUMBER,      
	HIRE_DATE,         
	JOB_ID,            
	SALARY,            
	COMMISSION_PCT,    
	MANAGER_ID,        
	DEPARTMENT_ID
FROM                   
	EMPLOYEES
WHERE
	FIRST_NAME LIKE '____%'
;

-- 28. 'SA_REP' 직무인 사원 중 가장 높은 월급과 가장 낮은 월급을 조회한다.
SELECT
	MAX(SALARY),
	MIN(SALARY)
FROM
	EMPLOYEES
WHERE
	JOB_ID = 'SA_REP'
;

-- 29. 직원의 입사일자를 '연-월-일' 형태로 조회한다.
SELECT
	TO_CHAR(HIRE_DATE, 'YYYY-MM-DD')
FROM                   
	EMPLOYEES
;

-- 30. 가장 늦게 입사한 사원의 모든 정보를 조회한다.
SELECT                 
	EMPLOYEE_ID,       
	FIRST_NAME,        
	LAST_NAME,         
	EMAIL,             
	PHONE_NUMBER,      
	HIRE_DATE,         
	JOB_ID,            
	SALARY,            
	COMMISSION_PCT,    
	MANAGER_ID,        
	DEPARTMENT_ID
FROM                   
	EMPLOYEES
WHERE
	HIRE_DATE = (
	SELECT
		MAX(TO_CHAR(HIRE_DATE, 'YYYY-MM-DD'))
	FROM
		EMPLOYEES)
;

-- 31. 가장 일찍 입사한 사원의 모든 정보를 조회한다.
SELECT                 
	EMPLOYEE_ID,       
	FIRST_NAME,        
	LAST_NAME,         
	EMAIL,             
	PHONE_NUMBER,      
	HIRE_DATE,         
	JOB_ID,            
	SALARY,            
	COMMISSION_PCT,    
	MANAGER_ID,        
	DEPARTMENT_ID
FROM                   
	EMPLOYEES
WHERE
	HIRE_DATE = (
	SELECT
		MIN(TO_CHAR(HIRE_DATE, 'YYYY-MM-DD'))
	FROM
		EMPLOYEES)
;

-- 32. 자신의 상사보다 더 많은 월급을 받는 사원의 모든 정보를 조회한다.
SELECT
	E.EMPLOYEE_ID,
	E.FIRST_NAME,
	E.LAST_NAME,
	E.EMAIL,
	E.PHONE_NUMBER,
	E.HIRE_DATE,
	E.JOB_ID,
	E.SALARY,
	E.COMMISSION_PCT,
	E.MANAGER_ID,
	E.DEPARTMENT_ID
FROM
	EMPLOYEES E
	-- 자신
JOIN 
    EMPLOYEES M
	-- 메니저
ON
	E.MANAGER_ID = M.EMPLOYEE_ID
WHERE
	E.SALARY > M.SALARY
;

-- 33. 자신의 상사보다 더 일찍 입사한 사원의 모든 정보를 조회한다.
SELECT
	E.EMPLOYEE_ID,
	E.FIRST_NAME,
	E.LAST_NAME,
	E.EMAIL,
	E.PHONE_NUMBER,
	E.HIRE_DATE,
	E.JOB_ID,
	E.SALARY,
	E.COMMISSION_PCT,
	E.MANAGER_ID,
	E.DEPARTMENT_ID
FROM
	EMPLOYEES E
	-- 자신
JOIN 
    EMPLOYEES M
	-- 메니저
ON
	E.MANAGER_ID = M.EMPLOYEE_ID
WHERE
	E.SALARY < M.SALARY
;

-- 34. 부서아이디별 평균 월급을 조회한다.
SELECT
	DEPARTMENT_ID,
	AVG(SALARY)
FROM
	EMPLOYEES
GROUP BY
	DEPARTMENT_ID
;
-- 35. 직무아이디별 평균 월급, 최고월급, 최저월급을 조회한다.
SELECT
	JOB_ID,
	AVG(SALARY),
	MAX(SALARY),
	MIN(SALARY)
FROM
	EMPLOYEES
GROUP BY
	JOB_ID
;

-- 36. 가장 많은 인센티브를 받는 사원의 모든 정보를 조회한다.
SELECT                 
	EMPLOYEE_ID,       
	FIRST_NAME,        
	LAST_NAME,         
	EMAIL,             
	PHONE_NUMBER,      
	HIRE_DATE,         
	JOB_ID,            
	SALARY,            
	COMMISSION_PCT,    
	MANAGER_ID,        
	DEPARTMENT_ID
FROM                   
	EMPLOYEES
WHERE
	COMMISSION_PCT >= (
	SELECT
		MAX(COMMISSION_PCT)
	FROM
		EMPLOYEES)
;

-- 37. 가장 적은 인센티브를 받는 사원의 월급과 인센티브를 조회한다.
SELECT                 
	EMPLOYEE_ID,       
	FIRST_NAME,        
	LAST_NAME,         
	EMAIL,             
	PHONE_NUMBER,      
	HIRE_DATE,         
	JOB_ID,            
	SALARY,            
	COMMISSION_PCT,    
	MANAGER_ID,        
	DEPARTMENT_ID
FROM                   
	EMPLOYEES
WHERE
	COMMISSION_PCT = (
	SELECT
		MIN(COMMISSION_PCT)
	FROM
		EMPLOYEES
	WHERE
		COMMISSION_PCT IS NOT NULL
)
;

-- 38. 직무아이디별 사원의 수를 조회한다.
SELECT
	JOB_ID,
	COUNT(EMPLOYEE_ID)
FROM
	EMPLOYEES
GROUP BY
	JOB_ID
;

-- 39. 상사아이디별 부하직원의 수를 조회한다. 단, 부하직원이 2명 이하인 경우는 제외한다.
SELECT
	MANAGER_ID,
	COUNT(EMPLOYEE_ID)
FROM                   
	EMPLOYEES
GROUP BY
	MANAGER_ID
HAVING
	COUNT(EMPLOYEE_ID) > 2
;

-- 40. 사원이 속한 부서의 평균월급보다 적게 받는 사원의 모든 정보를 조회한다.
SELECT
	E.EMPLOYEE_ID,
	E.FIRST_NAME,
	E.LAST_NAME,
	E.EMAIL,
	E.PHONE_NUMBER,
	E.HIRE_DATE,
	E.JOB_ID,
	E.SALARY,
	E.COMMISSION_PCT,
	E.MANAGER_ID,
	E.DEPARTMENT_ID
FROM
	EMPLOYEES E
WHERE
	E.SALARY < (
	SELECT
		AVG(SALARY)
	FROM
		EMPLOYEES
	WHERE
		DEPARTMENT_ID = E.DEPARTMENT_ID
    )
;

-- 41. 사원이 근무하는 부서명, 이름, 성을 조회한다. -- 106건
SELECT
	D.DEPARTMENT_NAME,
	E.FIRST_NAME,
	E.LAST_NAME
FROM
	EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
;

-- 42. 가장 적은 월급을 받는 사원의 부서명, 이름, 성, 월급, 부서장사원번호를 조회한다.
SELECT
	D.DEPARTMENT_NAME,
	E.FIRST_NAME,
	E.LAST_NAME,
	E.SALARY,
	D.MANAGER_ID
FROM
	EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE
	E.SALARY IN (
	SELECT
		MIN(SALARY)
	FROM
		EMPLOYEES)
;

-- 43. 상사사원번호를 중복없이 조회한다.
SELECT
	DISTINCT MANAGER_ID
FROM
	EMPLOYEES
;

-- 44. 50번 부서의 부서장의 이름, 성, 월급을 조회한다.
SELECT
	FIRST_NAME,
	LAST_NAME,
	SALARY
FROM
	EMPLOYEES
WHERE
	EMPLOYEE_ID = (
	SELECT
		MANAGER_ID
	FROM
		DEPARTMENTS
	WHERE
		DEPARTMENT_ID = 50
)
;

-- 45. 부서명별 사원의 수를 조회한다. -- 11
SELECT
	D.DEPARTMENT_NAME,
	COUNT(EMPLOYEE_ID)
FROM
	EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY
	D.DEPARTMENT_NAME
;
-- 46. 사원의 수가 가장 많은 부서명, 사원의 수를 조회한다.
SELECT
	D.DEPARTMENT_NAME,
	COUNT(EMPLOYEE_ID) AS CNT
FROM
	EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE
	ROWNUM = 1
GROUP BY
	D.DEPARTMENT_NAME
ORDER BY
	CNT DESC
;

SELECT
	DEPARTMENT_NAME,
	CNT
FROM
	(
	SELECT
		D.DEPARTMENT_NAME,
		COUNT(EMPLOYEE_ID) AS CNT
	FROM
		EMPLOYEES E
	INNER JOIN DEPARTMENTS D
ON
		E.DEPARTMENT_ID = D.DEPARTMENT_ID
	GROUP BY
		D.DEPARTMENT_NAME
	ORDER BY
		CNT DESC
)
WHERE
	ROWNUM = 1
;

-- 47. 사원이 없는 부서명을 조회한다.
SELECT
	D.DEPARTMENT_NAME
FROM
	DEPARTMENTS D
LEFT JOIN EMPLOYEES E
ON
	D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE
	E.EMPLOYEE_ID IS NULL
;

-- 48. 직무가 변경된 사원의 모든 정보를 조회한다.
SELECT                 
	E.EMPLOYEE_ID,       
	E.FIRST_NAME,        
	E.LAST_NAME,         
	E.EMAIL,             
	E.PHONE_NUMBER,      
	E.HIRE_DATE,         
	E.JOB_ID,            
	E.SALARY,            
	E.COMMISSION_PCT,    
	E.MANAGER_ID,        
	E.DEPARTMENT_ID
FROM                   
	EMPLOYEES E
JOIN JOB_HISTORY JH
ON
	E.EMPLOYEE_ID = JH.EMPLOYEE_ID
;

-- 49. 직무가 변경된적 없는 사원의 모든 정보를 조회한다.
SELECT                 
	EMPLOYEE_ID,       
	FIRST_NAME,        
	LAST_NAME,         
	EMAIL,             
	PHONE_NUMBER,      
	HIRE_DATE,         
	JOB_ID,            
	SALARY,            
	COMMISSION_PCT,    
	MANAGER_ID,        
	DEPARTMENT_ID
FROM                   
	EMPLOYEES
WHERE
	EMPLOYEE_ID NOT IN (
	SELECT
		EMPLOYEE_ID
	FROM
		JOB_HISTORY
)
;

-- 50. 직무가 변경된 사원의 과거 직무명과 현재 직무명을 조회한다. -- 10ROW
SELECT
	J_OLD.JOB_TITLE AS OLD_JOB_NAME,
	-- 과거 직무명
	J_CUR.JOB_TITLE AS CURRENT_JOB_NAME
	-- 현재 직무명
FROM
	EMPLOYEES E
JOIN JOB_HISTORY JH
    ON
	E.EMPLOYEE_ID = JH.EMPLOYEE_ID
JOIN JOBS J_OLD
    ON
	JH.JOB_ID = J_OLD.JOB_ID
JOIN JOBS J_CUR
    ON
	E.JOB_ID = J_CUR.JOB_ID
;

-- WITH : 잠깐 사용하고 말것들
SELECT
	DEPARTMENT_NAME
FROM
	(
	SELECT
		D.DEPARTMENT_NAME,
		COUNT(JH.JOB_ID) AS CHANGE_COUNT
	FROM
		JOB_HISTORY JH
	INNER JOIN DEPARTMENTS D
            ON
		JH.DEPARTMENT_ID = D.DEPARTMENT_ID
	GROUP BY
		D.DEPARTMENT_NAME
	ORDER BY
		CHANGE_COUNT DESC
    )
;

-- 52. 'Seattle' 에서 근무중인 사원의 이름, 성, 월급, 부서명 을 조회한다. - 18
-- 이 방법이 더 느리다
-- 조인으로 인하여 과정을 3개의 조인 후에 CITY = 'Seattle' 필터가 적용되어 느려진게 맞다.
-- 복접한 실행
-- L.CLTY를 조회한다면 이렇게 하는게 맞음.
SELECT
	E.FIRST_NAME,
	E.LAST_NAME,
	E.SALARY,
	D.DEPARTMENT_NAME
FROM
	EMPLOYEES E
INNER JOIN DEPARTMENTS D ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN LOCATIONS L ON
	D.LOCATION_ID = L.LOCATION_ID
WHERE
	L.CITY = 'Seattle'
;

-- LOCATIONS (CITY='Seattle')  -- 먼저 1행 추출
--        ↓
--DEPARTMENTS
--        ↓
--EMPLOYEE
-- 이렇게 작동하기 때문에 단순한 실행
SELECT
	E.FIRST_NAME,
	E.LAST_NAME,
	E.SALARY,
	D.DEPARTMENT_NAME
FROM
	EMPLOYEES E
INNER JOIN DEPARTMENTS D 
ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE 
	D.LOCATION_ID = (
	SELECT
		LOCATION_ID
	FROM
		LOCATIONS
	WHERE
		CITY = 'Seattle')
;

-- 53. 'Seattle' 에서 근무하지 않는 모든 사원의 이름, 성, 월급, 부서명, 도시를 조회한다. -- 88
SELECT
	E.FIRST_NAME,
	E.LAST_NAME,
	E.SALARY,
	D.DEPARTMENT_NAME,
	L.CITY
FROM
	EMPLOYEES E
INNER JOIN DEPARTMENTS D ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN LOCATIONS L ON
	D.LOCATION_ID = L.LOCATION_ID
WHERE
	L.CITY != 'Seattle'
;

-- 54. 근무중인 사원이 가장 많은 도시와 사원의 수를 조회한다. 
-- 	FETCH FIRST 1 ROWS ONLY  :
SELECT
	CITY,
	EMP_COUNT
FROM
	(
	SELECT
		L.CITY,
		COUNT(E.EMPLOYEE_ID) AS EMP_COUNT
	FROM
		EMPLOYEES E
	INNER JOIN DEPARTMENTS D ON
		E.DEPARTMENT_ID = D.DEPARTMENT_ID
	INNER JOIN LOCATIONS L ON
		D.LOCATION_ID = L.LOCATION_ID
	GROUP BY
		L.CITY
	ORDER BY
		EMP_COUNT DESC)
;

-- 55. 근무중인 사원이 없는 도시를 조회한다.
SELECT
	L.CITY
FROM
	LOCATIONS L
LEFT JOIN DEPARTMENTS D
    ON
	L.LOCATION_ID = D.LOCATION_ID
LEFT JOIN EMPLOYEES E
    ON
	D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY
	L.CITY
HAVING
	COUNT(E.EMPLOYEE_ID) = 0
;

-- 56. 월급이 7000 에서 12000 사이인 사원이 근무중인 도시를 조회한다.
SELECT
	CITY
FROM
	LOCATIONS L
JOIN DEPARTMENTS D
ON
	D.LOCATION_ID = L.LOCATION_ID
JOIN EMPLOYEES E
ON
	D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE
	E.SALARY BETWEEN 7000 AND 12000
;

-- 57. 'Seattle' 에서 근무중인 사원의 직무명을 중복없이 조회한다.
SELECT
	DISTINCT JOB_TITLE
FROM
	JOBS J
JOIN EMPLOYEES E
ON
	J.JOB_ID = E.JOB_ID
JOIN DEPARTMENTS D
ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L
ON
	D.LOCATION_ID = L.LOCATION_ID
WHERE
	L.CITY = 'Seattle'
;

-- 58. 사내의 최고월급과 최저월급의 차이를 조회한다.
SELECT
	MAX(SALARY) AS 최고월급,
	MIN(SALARY) AS 최저월급,
	MAX(SALARY) - MIN(SALARY) AS 차이
FROM
	EMPLOYEES
;

-- 59. 이름이 'Renske' 인 사원의 월급과 같은 월급을 받는 사원의 모든 정보를 조회한다. 단, 'Renske' 사원은 조회에서 제외한다.
SELECT
	E.FIRST_NAME,
	E.EMPLOYEE_ID,
	E.LAST_NAME,
	E.EMAIL,
	E.PHONE_NUMBER,
	E.HIRE_DATE,
	E.JOB_ID,
	E.SALARY,
	E.COMMISSION_PCT,
	E.MANAGER_ID,
	E.DEPARTMENT_ID
FROM
	EMPLOYEES E
JOIN EMPLOYEES R
ON
	E.SALARY = R.SALARY
WHERE
	R.FIRST_NAME = 'Renske'
	AND E.FIRST_NAME != 'Renske'
;

-- 60. 회사 전체의 평균 월급보다 많이 받는 사원들 중 이름에 'u' 가 포함된 사원과 동일한 부서에서 근무중인 사원들의 모든 정보를 조회한다.
SELECT
	EMPLOYEE_ID,       
	FIRST_NAME,        
	LAST_NAME,         
	EMAIL,             
	PHONE_NUMBER,      
	HIRE_DATE,         
	JOB_ID,            
	SALARY,            
	COMMISSION_PCT,    
	MANAGER_ID,        
	DEPARTMENT_ID
FROM
	EMPLOYEES
WHERE
	DEPARTMENT_ID IN (
	SELECT
		DEPARTMENT_ID
	FROM
		EMPLOYEES
	WHERE
		SALARY > (
		SELECT
			AVG(SALARY)
		FROM
			EMPLOYEES)
		AND FIRST_NAME LIKE '%u%'
)
;

-- 61. 부서가 없는 국가명을 조회한다.
SELECT
	COUNTRY_NAME
FROM
	COUNTRIES
WHERE
	COUNTRY_ID NOT IN (
	SELECT
		COUNTRY_ID
	FROM
		LOCATIONS
)
;

-- 62. 'Europe' 에서 근무중인 사원들의 모든 정보를 조회한다.
SELECT
	E.EMPLOYEE_ID,       
	E.FIRST_NAME,        
	E.LAST_NAME,         
	E.EMAIL,             
	E.PHONE_NUMBER,      
	E.HIRE_DATE,         
	E.JOB_ID,            
	E.SALARY,            
	E.COMMISSION_PCT,    
	E.MANAGER_ID,        
	E.DEPARTMENT_ID
FROM
	EMPLOYEES E
JOIN DEPARTMENTS D
  ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L
  ON
	D.LOCATION_ID = L.LOCATION_ID
JOIN COUNTRIES C
  ON
	L.COUNTRY_ID = C.COUNTRY_ID
JOIN REGIONS R
  ON
	C.REGION_ID = R.REGION_ID
WHERE
	R.REGION_NAME = 'Europe'
;

-- 63. 'Europe'에서 가장 많은 사원들이 있는 부서명을 조회한다. 
-- 더 빠른 조회를 이용한것은 조인을 하지 않느 방법
SELECT
	DEPARTMENT_NAME
FROM
	(
	SELECT
		D.DEPARTMENT_NAME,
		COUNT(E.EMPLOYEE_ID) AS EMP_COUNT
	FROM
		EMPLOYEES E
	INNER JOIN DEPARTMENTS D
            ON
		E.DEPARTMENT_ID = D.DEPARTMENT_ID
	INNER JOIN LOCATIONS L
            ON
		D.LOCATION_ID = L.LOCATION_ID
	INNER JOIN COUNTRIES C
            ON
		L.COUNTRY_ID = C.COUNTRY_ID
	INNER JOIN REGIONS R
            ON
		C.REGION_ID = R.REGION_ID
	WHERE
		R.REGION_NAME = 'Europe'
	GROUP BY
		D.DEPARTMENT_NAME
	ORDER BY
		EMP_COUNT DESC
    )
;

-- 64. 대륙 별 사원의 수를 조회한다. -2
SELECT
	R.REGION_ID,
	COUNT(EMPLOYEE_ID)
FROM
	EMPLOYEES E
INNER JOIN DEPARTMENTS D
  ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN LOCATIONS L
  ON
	D.LOCATION_ID = L.LOCATION_ID
INNER JOIN COUNTRIES C
  ON
	L.COUNTRY_ID = C.COUNTRY_ID
INNER JOIN REGIONS R
  ON
	C.REGION_ID = R.REGION_ID
GROUP BY
	R.REGION_ID
;

-- 65. 월급이 2500, 3500, 7000 이 아니며 직업이 SA_REP 이나 ST_CLERK 인 사람들을 조회한다.
SELECT
	JOB_ID,
	SALARY
FROM
	EMPLOYEES
WHERE
	SALARY != 2500
	AND SALARY != 3500
	AND SALARY != 7000
	AND(JOB_ID = 'SA_REP'
		OR JOB_ID = 'ST_CLERK')
;

SELECT
	JOB_ID,
	SALARY
FROM
	EMPLOYEES
WHERE
	SALARY NOT IN (2500, 3500, 7000)
	AND JOB_ID IN('SA_REP', 'ST_CLERK') 
;

-- 65-1. 월급이 2500, 3500, 7000 이 아닌 사원들의 사원 번호와 월급을 조회한다.
-- IN : 각각의 값들을 다 가져온다 IN 2500 OR 3500 OR 7000
-- SALARY != 2500 AND SALARY != 3500 AND SALARY != 7000 => SALARY NOT IN (2500, 3500, 7000) !=를 의미
SELECT
	EMPLOYEE_ID,
	SALARY
FROM
	EMPLOYEES
WHERE
	SALARY NOT IN (2500, 3500, 7000)
;

-- 65-2. 직무아이디가 SA_REP 이거나 ST_CLERK 인 사원들의 사원번호와 직무아이디를 조회한다.
SELECT
	EMPLOYEE_ID,
	JOB_ID
FROM
	EMPLOYEES
WHERE
	JOB_ID IN('SA_REP', 'ST_CLERK') 
;

-- 66. 사원의 사원번호, 이름, 성, 상사의 사원번호, 상사의 이름, 상사의 성을 조회한다. - 106ROW
SELECT
	E.EMPLOYEE_ID,
	E.FIRST_NAME,
	E.LAST_NAME,
	M.EMPLOYEE_ID,
	M.FIRST_NAME,
	M.LAST_NAME
FROM
	EMPLOYEES E
INNER JOIN EMPLOYEES M ON
	M.EMPLOYEE_ID = E.MANAGER_ID
;

-- 67. 101번 사원의 모든 부하직원 들의 이름, 성, 상사사원번호, 상사사원명을 조회한다.
SELECT
	LEVEL,
	EMP.EMPLOYEE_ID,
	EMP.FIRST_NAME,
	EMP.LAST_NAME,
	EMP.MANAGER_ID,
	MAN.FIRST_NAME,
	MAN.LAST_NAME
FROM
	EMPLOYEES EMP
INNER JOIN EMPLOYEES MAN
ON
	EMP.MANAGER_ID = MAN.EMPLOYEE_ID
START WITH
	EMP.EMPLOYEE_ID = 101
	-- 조인을 했을때 기준 테이블 하나로만 나타내어야함.
CONNECT BY
	PRIOR EMP.EMPLOYEE_ID = EMP.MANAGER_ID
	-- 부하 조회
;

-- 68. 114번 직원의 모든 상사들의 이름, 성, 사원번호을 조회한다.
SELECT
	LEVEL,
	MAN.EMPLOYEE_ID,
	MAN.FIRST_NAME,
	MAN.LAST_NAME
FROM
	EMPLOYEES EMP
INNER JOIN EMPLOYEES MAN
ON
	EMP.MANAGER_ID = MAN.EMPLOYEE_ID
START WITH
	EMP.EMPLOYEE_ID = 114
	-- 조인을 했을때 기준 테이블 하나로만 나타내어야함.
CONNECT BY
	PRIOR EMP.MANAGER_ID = EMP.EMPLOYEE_ID
	-- 상사 조회
;

-- 69. 114번 직원의 모든 상사들의 이름, 성, 사원번호을 조회한다. 단, 역순으로 조회한다.
SELECT
	LEVEL,
	MAN.EMPLOYEE_ID,
	MAN.FIRST_NAME,
	MAN.LAST_NAME
FROM
	EMPLOYEES EMP
INNER JOIN EMPLOYEES MAN
ON
	EMP.MANAGER_ID = MAN.EMPLOYEE_ID
START WITH
	EMP.EMPLOYEE_ID = 114
	-- 조인을 했을때 기준 테이블 하나로만 나타내어야함.
CONNECT BY
	PRIOR EMP.MANAGER_ID = EMP.EMPLOYEE_ID
ORDER BY
	LEVEL DESC
;

-- 70. 모든 사원(EMPLOYEES)들의 정보를 월급(SALARY) 오름차순 정렬하여 조회한다.
SELECT
	EMPLOYEE_ID,
	FIRST_NAME,
	LAST_NAME,
	EMAIL,
	PHONE_NUMBER,
	HIRE_DATE,
	JOB_ID,
	SALARY,
	COMMISSION_PCT,
	MANAGER_ID,
	DEPARTMENT_ID
FROM
	EMPLOYEES
ORDER BY
	SALARY ASC 
;

-- 71. 모든 사원(EMPLOYEES)들을 이름(LAST_NAME) 내림차순 정렬하여 조회한다.
SELECT
	EMPLOYEE_ID,
	FIRST_NAME,
	LAST_NAME,
	EMAIL,
	PHONE_NUMBER,
	HIRE_DATE,
	JOB_ID,
	SALARY,
	COMMISSION_PCT,
	MANAGER_ID,
	DEPARTMENT_ID
FROM
	EMPLOYEES
ORDER BY
	LAST_NAME DESC
;

-- 72. 모든 사원들의 이름, 성, 월급, 부서명을 부서번호로 내림차순 정렬하여 조회한다.
SELECT
	E.LAST_NAME,
	-- 성
	E.FIRST_NAME,
	-- 이름
	E.SALARY,
	-- 월급(주급)
	D.DEPARTMENT_NAME
	-- 부서명
FROM
	EMPLOYEES E
INNER JOIN
    DEPARTMENTS D
ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY
	D.DEPARTMENT_ID DESC
	-- 내림차순
;

-- 73. 부서명별 월급의 합을 내림차순 정렬하여 조회한다. -- 11
SELECT
	D.DEPARTMENT_NAME,
	SUM(E.SALARY) AS SUM
FROM
	EMPLOYEES E
INNER JOIN
    DEPARTMENTS D
ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY
	D.DEPARTMENT_NAME
ORDER BY
	SUM DESC
 ;

-- 74. 직무명별 사원의 수를 오름차순 정렬하여 조회한다. -19
SELECT
	J.JOB_TITLE,
	COUNT(E.EMPLOYEE_ID) AS COUNT
FROM
	EMPLOYEES E
INNER JOIN
    JOBS J
ON
	E.JOB_ID = J.JOB_ID
GROUP BY
	J.JOB_TITLE
ORDER BY
	COUNT ASC
 ;

-- 75. 모든 사원들의 모든 정보를 조회한다. 단, 인센티브를 받는 사원은 "인센티브여부" 컬럼에 "Y"를, 아닌 경우 "N"으로 조회한다.
SELECT
	COMMISSION_PCT,
	-- 값 동등 비교 / 크다, 작다, 다르다 등의 비교가 가능하다.
	CASE
		WHEN COMMISSION_PCT IS NOT NULL THEN 'Y'
		ELSE 'N'
	END AS 인센티브여부,
	-- 값을 비교할때 동등 비교만 가능 : 인센티브여부2는
	CASE
		NVL(COMMISSION_PCT, 0)
		WHEN 0 THEN 'N'
		ELSE 'Y'
	END AS 인센티브여부2 ,
	EMPLOYEE_ID,
	FIRST_NAME,
	LAST_NAME,
	EMAIL,
	PHONE_NUMBER,
	HIRE_DATE,
	JOB_ID,
	SALARY,
	MANAGER_ID,
	DEPARTMENT_ID
FROM
	EMPLOYEES
;

-- 76. 모든 사원들의 이름을 10자리로 맞추어 조회한다.
SELECT
	LPAD(FIRST_NAME, 10)
FROM
	EMPLOYEES
;

-- 77. 2007년에 직무가 변경된 사원들의 현재 직무명, 부서명, 사원번호, 이름, 성을 조회한다. --2ROW
SELECT
	J.JOB_TITLE,
	D.DEPARTMENT_NAME,
	E.EMPLOYEE_ID,
	E.FIRST_NAME,
	E.LAST_NAME
FROM
	EMPLOYEES E
INNER JOIN DEPARTMENTS D
    ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN JOBS J
    ON
	E.JOB_ID = J.JOB_ID
WHERE
	E.EMPLOYEE_ID IN (
	SELECT
		EMPLOYEE_ID
	FROM
		JOB_HISTORY
	WHERE
		START_DATE BETWEEN TO_DATE('2007-01-01', 'YYYY-MM-DD')
                            AND TO_DATE('2007-12-31', 'YYYY-MM-DD')
    )
;

-- 78. 직무별 최대월급보다 더 많은 월급을 받는 사원의 모든 정보를 조회한다.
SELECT
	E.EMPLOYEE_ID,
	E.FIRST_NAME,
	E.LAST_NAME,
	E.EMAIL,
	E.PHONE_NUMBER,
	E.HIRE_DATE,
	E.JOB_ID,
	E.SALARY,
	E.COMMISSION_PCT,
	E.MANAGER_ID,
	E.DEPARTMENT_ID
FROM
	EMPLOYEES E
JOIN JOBS J
ON
	E.JOB_ID = J.JOB_ID
WHERE
	E.SALARY > J.MAX_SALARY
;

-- 79. 사원들의 입사일자 중 이름, 성, 연도만 조회한다.
SELECT
	FIRST_NAME,
	LAST_NAME,
	TO_CHAR(HIRE_DATE, 'YYYY')
FROM
	EMPLOYEES
;

-- 80. 사원들의 입사일자 중 이름, 성, 입사월을 조회한다.
SELECT
	FIRST_NAME,
	LAST_NAME,
	TO_CHAR(HIRE_DATE, 'MM')
FROM
	EMPLOYEES
;

-- 81. 100번 사원의 모든 부하직원을 계층조회한다. 단, LEVEL이 4인 사원은 제외한다.
SELECT
	LEVEL,
	EMPLOYEE_ID
FROM
	EMPLOYEES
START WITH
	EMPLOYEE_ID = 100
CONNECT BY
	PRIOR EMPLOYEE_ID = MANAGER_ID
HAVING
	LEVEL != 4
;

-- 82. 많은 월급을 받는 10명을 조회한다.
SELECT
	EMPLOYEE_ID,
	FIRST_NAME,
	LAST_NAME,
	EMAIL,
	PHONE_NUMBER,
	HIRE_DATE,
	JOB_ID,
	SALARY,
	COMMISSION_PCT,
	MANAGER_ID,
	DEPARTMENT_ID
FROM
	(
	SELECT
		EMPLOYEE_ID,
		FIRST_NAME,
		LAST_NAME,
		EMAIL,
		PHONE_NUMBER,
		HIRE_DATE,
		JOB_ID,
		SALARY,
		COMMISSION_PCT,
		MANAGER_ID,
		DEPARTMENT_ID
	FROM
		EMPLOYEES
	ORDER BY
		SALARY DESC
    )
WHERE
	ROWNUM <= 10
;

-- 83. 가장 적은 월급을 받는 사원의 상사명, 사원의 부서명을 조회한다. - 1건
SELECT
	M.EMPLOYEE_ID,
	M.FIRST_NAME,
	D.DEPARTMENT_NAME
FROM
	EMPLOYEES E
INNER JOIN EMPLOYEES M
ON
	M.EMPLOYEE_ID = E.MANAGER_ID
INNER JOIN DEPARTMENTS D
ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE
	E.SALARY = (
	SELECT
		MIN(SALARY)
	FROM
		EMPLOYEES)
;

-- 84. 많은 월급을 받는 사원 중 11번 째 부터 20번째를 조회한다.
-- ROWNUM은 FETCHED 과정에서 만들어진다
-- 페이지네비게이션
SELECT
	R_NUM,
	EMPLOYEE_ID,
	FIRST_NAME,
	LAST_NAME,
	EMAIL,
	PHONE_NUMBER,
	HIRE_DATE,
	JOB_ID,
	SALARY,
	COMMISSION_PCT,
	MANAGER_ID,
	DEPARTMENT_ID
FROM
	(
	SELECT
		ROWNUM AS R_NUM,
		EMPLOYEE_ID,
		FIRST_NAME,
		LAST_NAME,
		EMAIL,
		PHONE_NUMBER,
		HIRE_DATE,
		JOB_ID,
		SALARY,
		COMMISSION_PCT,
		MANAGER_ID,
		DEPARTMENT_ID
	FROM
		(
		SELECT
			EMPLOYEE_ID,
			FIRST_NAME,
			LAST_NAME,
			EMAIL,
			PHONE_NUMBER,
			HIRE_DATE,
			JOB_ID,
			SALARY,
			COMMISSION_PCT,
			MANAGER_ID,
			DEPARTMENT_ID
		FROM
			EMPLOYEES
		ORDER BY
			SALARY DESC)
	WHERE
		ROWNUM <= 20
	ORDER BY
		ROWNUM ASC
	)
WHERE
	R_NUM >= 11
;

-- 85. 가장 적은 월급을 받는 중 90번 째 부터 100번째를 조회한다.
SELECT
	R_NUM,
	SALARY
FROM
	(
	SELECT
		ROWNUM AS R_NUM,
		SALARY
	FROM
		(
		SELECT
			SALARY
		FROM
			EMPLOYEES
		ORDER BY
			SALARY ASC)
	WHERE
		ROWNUM <= 100
	ORDER BY
		ROWNUM ASC
	)
WHERE
	R_NUM >= 90
;

-- 86. 'PU_CLERK' 직무인 2번째 부터 5번째 사원의 부서명, 직무명을 조회한다.
SELECT
	DEPARTMENT_NAME,
	JOB_TITLE
FROM
	(
	SELECT
		D.DEPARTMENT_NAME,
		J.JOB_TITLE,
		ROWNUM AS R_NUM
	FROM
		EMPLOYEES E
	INNER JOIN DEPARTMENTS D
	ON
		E.DEPARTMENT_ID = D.DEPARTMENT_ID
	INNER JOIN JOBS J
	ON
		E.JOB_ID = J.JOB_ID
	WHERE
		J.JOB_ID = 'PU_CLERK'
		AND ROWNUM <= 5
	)
WHERE
	R_NUM >= 2
;

SELECT 
		D.DEPARTMENT_NAME,
		J.JOB_TITLE
FROM
	(
	SELECT
		R_NUM,
		DEPARTMENT_ID,
		JOB_ID
	FROM
		(
		SELECT
			ROWNUM AS R_NUM,
			DEPARTMENT_ID,
			JOB_ID
		FROM
			(
			SELECT
				DEPARTMENT_ID,
				JOB_ID
			FROM
				EMPLOYEES
			WHERE
				JOB_ID = 'PU_CLERK'
			)
		WHERE
			ROWNUM <= 5
		)
	WHERE
		R_NUM >= 2
	) EMP
INNER JOIN DEPARTMENTS D
	ON
		EMP.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN JOBS J
	ON
		EMP.JOB_ID = J.JOB_ID
;

-- 87. 모든 사원의 정보를 직무 오름차순, 월급 내림차순으로 조회한다.
SELECT
	EMPLOYEE_ID,
	FIRST_NAME,
	LAST_NAME,
	EMAIL,
	PHONE_NUMBER,
	HIRE_DATE,
	JOB_ID AS JOBS,
	SALARY AS SALARY,
	COMMISSION_PCT,
	MANAGER_ID,
	DEPARTMENT_ID
FROM
	EMPLOYEES
ORDER BY
	JOBS ASC,
	SALARY DESC
;

-- 88. 직무별 평균월급을 평균월급순으로 오름차순 정렬하여 조회한다.
-- 직무 아이디, 평균 월급
SELECT
	JOB_ID,
	AVG(SALARY) AS AVG_SALARY
FROM
	EMPLOYEES
GROUP BY
	JOB_ID
ORDER BY
	AVG_SALARY ASC 
;

-- 89. 부서별 평균월급을 내림차순 정렬하여 조회한다.
SELECT
	DEPARTMENT_ID,
	AVG(SALARY) AS SALARY
FROM
	EMPLOYEES
GROUP BY
	DEPARTMENT_ID
ORDER BY
	SALARY DESC
;

-- 90. 이름의 첫 번째 글자별 평균월급을 조회한다.
-- SUBSTR : 문자열에서 특정 위치부터 지정한 길이만큼 문자열을 추출
SELECT
	FIRST_CHAR,
	AVG(SALARY) AS SALARY
FROM
	(
	SELECT
		SUBSTR(FIRST_NAME, 1, 1) AS FIRST_CHAR,
		SALARY
	FROM
		EMPLOYEES)
GROUP BY
	FIRST_CHAR
;

-- 91. 입사연도별 최소월급을 조회한다.
SELECT
	HIRE_YEAR,
	MIN(SALARY) AS MIN_SALARY
FROM
	(
	SELECT
		TO_CHAR(HIRE_DATE, 'YYYY') AS HIRE_YEAR,
		SALARY
	FROM
		EMPLOYEES)
GROUP BY
	HIRE_YEAR
;

-- 92. 월별 최대월급 중 2번째 부터 4번째 데이터만 조회한다. 
SELECT
	R_NUM,
	HIRE_MONTH,
	MAX_SALARY
FROM
	(
	SELECT
		ROWNUM AS R_NUM,
		T.HIRE_MONTH,
		T.MAX_SALARY
	FROM
		(
		SELECT
			HIRE_MONTH,
			MAX(SALARY) AS MAX_SALARY
		FROM
			(
			SELECT
				TO_CHAR(HIRE_DATE, 'MM') AS HIRE_MONTH,
				SALARY
			FROM
				EMPLOYEES)
		GROUP BY
			HIRE_MONTH
		ORDER BY
			MAX_SALARY DESC) T
	WHERE
		ROWNUM <= 4
 	)
WHERE
	R_NUM >= 2
;

-- 93. 직무명별 최소월급을 조회한다.- 19
SELECT
	J.JOB_TITLE,
	MIN(E.SALARY) AS MIN
FROM
	EMPLOYEES E
INNER JOIN JOBS J
ON
	E.JOB_ID = J.JOB_ID
GROUP BY
	J.JOB_TITLE
;

SELECT
	JOB_TITLE,
	MIN(MIN_SALARY)
FROM
	JOBS
GROUP BY
	JOB_TITLE
;

-- 94. 부서명별 최대월급을 조회한다. --11
SELECT
	D.DEPARTMENT_NAME,
	MAX(E.SALARY)
FROM
	EMPLOYEES E
INNER JOIN DEPARTMENTS D
	ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY
	D.DEPARTMENT_NAME
;

-- 95. 직무명, 부서명 별 사원 수, 평균월급을 조회한다. -19
SELECT
	J.JOB_TITLE,
	D.DEPARTMENT_NAME,
	COUNT(E.EMPLOYEE_ID),
	AVG(E.SALARY)
FROM
	EMPLOYEES E
INNER JOIN DEPARTMENTS D
	ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN JOBS J
ON
	E.JOB_ID = J.JOB_ID
GROUP BY
	D.DEPARTMENT_NAME,
	J.JOB_TITLE
;

-- 96. 도시별 사원 수를 조회한다. - 7
SELECT
	L.CITY,
	COUNT(E.EMPLOYEE_ID)
FROM
	EMPLOYEES E
INNER JOIN DEPARTMENTS D
	ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN LOCATIONS L
ON
	D.LOCATION_ID = L.LOCATION_ID
GROUP BY
	L.CITY
;

-- 97. 국가별 사원 수, 최대월급, 최소월급을 조회한다. - 4
SELECT
	C.COUNTRY_ID,
	COUNT(E.EMPLOYEE_ID) AS EMP_CNT,
	MAX(E.SALARY) AS MAX_SALARY,
	MIN(E.SALARY) AS MIN_SALARY
FROM
	EMPLOYEES E
INNER JOIN DEPARTMENTS D
    ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN LOCATIONS L
    ON
	D.LOCATION_ID = L.LOCATION_ID
INNER JOIN COUNTRIES C
    ON
	L.COUNTRY_ID = C.COUNTRY_ID
GROUP BY
	C.COUNTRY_ID
;

-- 98. 대륙별 사원 수를 대륙명으로 오름차순 정렬하여 조회한다. - 2
SELECT
	R.REGION_NAME,
	COUNT(E.EMPLOYEE_ID)
FROM
	EMPLOYEES E
INNER JOIN DEPARTMENTS D
    ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN LOCATIONS L
    ON
	D.LOCATION_ID = L.LOCATION_ID
INNER JOIN COUNTRIES C
    ON
	L.COUNTRY_ID = C.COUNTRY_ID
INNER JOIN REGIONS R
ON
	C.REGION_ID = R.REGION_ID
GROUP BY
	R.REGION_NAME
ORDER BY
	R.REGION_NAME ASC
;

-- 99. 이름이나 성에 'A' 혹은 'a' 가 포함된 사원의 모든 정보를 조회한다.
SELECT
	EMPLOYEE_ID,
	FIRST_NAME,
	LAST_NAME,
	EMAIL,
	PHONE_NUMBER,
	HIRE_DATE,
	JOB_ID AS JOBS,
	SALARY AS SALARY,
	COMMISSION_PCT,
	MANAGER_ID,
	DEPARTMENT_ID
FROM
	EMPLOYEES
WHERE
	FIRST_NAME LIKE '%A%'
	OR FIRST_NAME LIKE '%a%'
	OR LAST_NAME LIKE '%A%'
	OR LAST_NAME LIKE '%a%'
;

-- 100. 국가별로 월급이 5000 이상인 사원의 수를 조회한다. - 4
SELECT
	C.COUNTRY_NAME,
	COUNT(E.EMPLOYEE_ID)
FROM
	EMPLOYEES E
INNER JOIN DEPARTMENTS D
    ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN LOCATIONS L
    ON
	D.LOCATION_ID = L.LOCATION_ID
INNER JOIN COUNTRIES C
    ON
	L.COUNTRY_ID = C.COUNTRY_ID
WHERE
	E.SALARY >= 5000
GROUP BY
	C.COUNTRY_NAME
;

-- 101. 인센티브를 안받는 사원이 근무하는 도시를 조회한다.
SELECT
	L.CITY
FROM
	LOCATIONS L
INNER JOIN DEPARTMENTS D
ON
	L.LOCATION_ID = D.LOCATION_ID
INNER JOIN EMPLOYEES E
ON
	D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE
	E.COMMISSION_PCT IS NULL
;

-- 102. 인센티브를 포함한 월급이 10000 이상인 사원의 모든 정보를 조회한다.
-- 조금 더 빠른 조회가 가능하다
SELECT
	*
FROM
	(
	SELECT
		EMPLOYEE_ID,
		FIRST_NAME,
		LAST_NAME,
		EMAIL,
		PHONE_NUMBER,
		HIRE_DATE,
		JOB_ID,
		SALARY + SALARY * NVL(COMMISSION_PCT, 0) AS TOTAL_SALARY,
		COMMISSION_PCT,
		MANAGER_ID,
		DEPARTMENT_ID
	FROM
		EMPLOYEES)
WHERE
	TOTAL_SALARY >= 10000
	;

-- 103. 가장 많은 부서가 있는 도시를 조회한다.
SELECT
	CITY,
	DEP_COUNT
FROM
	(
	SELECT
		L.CITY,
		COUNT(D.DEPARTMENT_ID) AS DEP_COUNT
	FROM
		DEPARTMENTS D
	INNER JOIN LOCATIONS L
            ON
		D.LOCATION_ID = L.LOCATION_ID
	GROUP BY
		L.CITY
	ORDER BY
		DEP_COUNT DESC
    )
WHERE
	ROWNUM = 1
;

-- 104. 가장 많은 사원이 있는 부서의 국가명을 조회한다.
-- 성능을 위주로 한다면 조인을 자제하고 만드는것이 좋다.
SELECT
	COUNTRY_NAME
FROM
	(
	SELECT
			C.COUNTRY_NAME,
			COUNT(E.EMPLOYEE_ID) AS EMP_COUNT
	FROM
			EMPLOYEES E
	INNER JOIN DEPARTMENTS D
            ON
			E.DEPARTMENT_ID = D.DEPARTMENT_ID
	INNER JOIN LOCATIONS L
            ON
			D.LOCATION_ID = L.LOCATION_ID
	INNER JOIN COUNTRIES C
  			ON
			L.COUNTRY_ID = C.COUNTRY_ID
	GROUP BY
			C.COUNTRY_NAME
	ORDER BY
			EMP_COUNT DESC
    )
WHERE
	ROWNUM = 1
;

-- 105. 우편번호가 5자리인 도시에서 근무하는 사원명, 부서명, 도시명, 우편번호를 조회한다. -- 69ROW
SELECT
	E.FIRST_NAME,
	D.DEPARTMENT_NAME,
	L.CITY,
	L.POSTAL_CODE
FROM
	LOCATIONS L
INNER JOIN DEPARTMENTS D
ON
	L.LOCATION_ID = D.LOCATION_ID
INNER JOIN EMPLOYEES E
ON
	D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE
	L.POSTAL_CODE LIKE '_____'
;

-- 106. 우편번호에 공백이 없는 도시에서 근무하는 사원의 이름, 부서명, 우편번호를 조회한다. - 69ROW
SELECT
	E.FIRST_NAME,
	D.DEPARTMENT_NAME,
	L.CITY,
	L.POSTAL_CODE
FROM
	LOCATIONS L
INNER JOIN DEPARTMENTS D
ON
	L.LOCATION_ID = D.LOCATION_ID
INNER JOIN EMPLOYEES E
ON
	D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE
	L.POSTAL_CODE NOT LIKE '% %'
;

-- 107. "주"가 없는 도시에서 근무하는 사원의 이름, 도시를 조회한다. -- 1ROW
SELECT
	E.FIRST_NAME,
	L.LOCATION_ID
FROM
	LOCATIONS L
INNER JOIN DEPARTMENTS D
ON
	L.LOCATION_ID = D.LOCATION_ID
INNER JOIN EMPLOYEES E
ON
	D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE
	L.STATE_PROVINCE IS NULL
;

-- 108. 국가명이 6자리인 국가의 모든 정보를 조회한다.
SELECT
	COUNTRY_ID,
	COUNTRY_NAME,
	REGION_ID
FROM
	COUNTRIES
WHERE
	COUNTRY_NAME LIKE '______'
;

-- 109. 사원의 이름과 성을 이용해 EMAIL과 같은 값으로 만들어 조회한다.
-- - (FIRST_NAME의 첫번째 글자 + LAST_NAME의 7글자(공백제거)) 최대 8글자
SELECT
	FIRST_NAME,
	LAST_NAME,
	UPPER(SUBSTR(FIRST_NAME, 1, 1)) || UPPER(SUBSTR(REPLACE(LAST_NAME, ' ', ''), 1, 7)) AS EMAIL_LIKE
FROM
	EMPLOYEES
;

-- 110. 모든 사원들의 이름을 10자리로 변환해 조회한다. 예> 이름 => "        이름"
SELECT
	LPAD(FIRST_NAME, 10, ' ')
FROM
	EMPLOYEES
;

-- 111. 모든 사원들의 성을 10자리로 변환해 조회한다. 예> 성 => "성         "
SELECT
	RPAD(LAST_NAME, 10, '*')
FROM
	EMPLOYEES
;

-- 112. 109번 사원의 입사일 부터 1년 내에 입사한 사원의 모든 정보를 조회한다.
SELECT
	EMPLOYEE_ID,       
	FIRST_NAME,        
	LAST_NAME,         
	EMAIL,             
	PHONE_NUMBER,      
	HIRE_DATE,         
	JOB_ID,            
	SALARY,            
	COMMISSION_PCT,    
	MANAGER_ID,        
	DEPARTMENT_ID
FROM
	EMPLOYEES
WHERE
	HIRE_DATE BETWEEN
    (
	SELECT
		HIRE_DATE
	FROM
		EMPLOYEES
	WHERE
		EMPLOYEE_ID = 109)
AND
    ADD_MONTHS((SELECT HIRE_DATE FROM EMPLOYEES WHERE EMPLOYEE_ID = 109), 12)
;

-- 113. 가장 먼저 입사한 사원의 입사일로부터 2년 내에 입사한사원의 모든 정보를 조회한다.
SELECT
	EMPLOYEE_ID,
	FIRST_NAME,
	LAST_NAME,
	EMAIL,
	PHONE_NUMBER,
	HIRE_DATE,
	JOB_ID,
	SALARY,
	COMMISSION_PCT,
	MANAGER_ID,
	DEPARTMENT_ID
FROM
	EMPLOYEES
WHERE
	HIRE_DATE BETWEEN
        (
	SELECT
		MIN(HIRE_DATE)
	FROM
		EMPLOYEES)
    AND
        (
	SELECT
		ADD_MONTHS(MIN(HIRE_DATE), 24)
	FROM
		EMPLOYEES)
;

-- 114. 가장 늦게 입사한 사원의 입사일 보다 1년 앞서 입사한 사원의 모든 정보를 조회한다.
SELECT
	EMPLOYEE_ID,
	FIRST_NAME,
	LAST_NAME,
	EMAIL,
	PHONE_NUMBER,
	HIRE_DATE,
	JOB_ID,
	SALARY,
	COMMISSION_PCT,
	MANAGER_ID,
	DEPARTMENT_ID
FROM
	EMPLOYEES
WHERE
	HIRE_DATE BETWEEN
        (
	SELECT
		ADD_MONTHS(MAX(HIRE_DATE), -12)
	FROM
		EMPLOYEES)
    AND
        (
	SELECT
		MAX(HIRE_DATE)
	FROM
		EMPLOYEES)
;

-- 115. 도시명에 띄어쓰기 " " 가 포함된 도시에서 근무중인 사원들의 부서명, 도시명, 사원명을 조회한다. - 45ROW
SELECT
	E.FIRST_NAME,
	D.DEPARTMENT_NAME,
	L.CITY
FROM
	LOCATIONS L
INNER JOIN DEPARTMENTS D
ON
	L.LOCATION_ID = D.LOCATION_ID
INNER JOIN EMPLOYEES E
ON
	D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE
	L.CITY LIKE '% %'
;

-- 116. MOD 함수를 통해 사원번호가 홀수면 남자, 짝수면 여자 로 구분해 조회한다. MOD(값, 나눌값)
SELECT
	EMPLOYEE_ID,
	MOD(EMPLOYEE_ID, 2),
	CASE
		WHEN MOD(EMPLOYEE_ID, 2) = 0 THEN '여자'
		ELSE '남자'
	END AS 성별
FROM
	EMPLOYEES
;

-- 117. '20230222' 문자 데이터를 날짜로 변환해 조회한다.(DUAL)
SELECT
	TO_DATE('20230222', 'YYYYMMDD')
FROM
	DUAL;

-- 118. '20230222' 문자 데이터를 'YYYY-MM' 으로 변환해 조회한다.(DUAL)
SELECT
	TO_CHAR(TO_DATE('20230222', 'YYYY-MM-DD'), 'YYYY-MM')
FROM
	DUAL;

-- 119. '20230222130140' 문자 데이터를 'YYYY-MM-DD HH24:MI:SS' 으로 변환해 조회한다. (DUAL)
SELECT
	TO_CHAR(TO_DATE('20230222130140', 'YYYY-MM-DDHH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS')
FROM
	DUAL;

-- 120. '20230222' 날짜의 열흘 후의 날짜를 'YYYY-MM-DD' 으로 변환해 조회한다. (DUAL)
SELECT
	TO_CHAR(TO_DATE('20230222', 'YYYY-MM-DD'), 'YYYY-MM-DD')
FROM
	DUAL;

-- 121. 사원 이름의 글자수 별 사원의 수를 조회한다.
SELECT
	COUNT(EMPLOYEE_ID) AS NAME_LENGTH,
	COUNT_NAME
FROM
	(
	SELECT
		EMPLOYEE_ID,
		LENGTH(FIRST_NAME) AS COUNT_NAME
	FROM
		EMPLOYEES)
GROUP BY
	COUNT_NAME
;

-- 122. 사원 성의 글자수 별 사원의 수를 조회한다.
SELECT
	COUNT(EMPLOYEE_ID) AS NAME_LENGTH,
	NAME
FROM
	(
	SELECT
		EMPLOYEE_ID,
		LENGTH(LAST_NAME) AS NAME
	FROM
		EMPLOYEES)
GROUP BY
	NAME
;

-- 123. 사원의 월급이 5000 이하이면 "사원", 7000 이하이면 "대리", 9000 이하이면 "과장", 그 외에는 임원 으로 조회한다.
SELECT
	EMPLOYEE_ID,
	SALARY,
	CASE
		WHEN SALARY <= 5000 THEN '사원'
		WHEN SALARY <= 7000 THEN '대리'
		WHEN SALARY <= 9000 THEN '과장'
		ELSE '임원'
	END AS 직급
FROM
	EMPLOYEES
;

-- 124. 부서별 사원의 수를 조인을 이용해 다음과 같이 조회한다."부서명 (사원의 수)"
SELECT
	D.DEPARTMENT_ID,
	COUNT(E.EMPLOYEE_ID),
	D.DEPARTMENT_ID || ' ' || '(' || COUNT(E.EMPLOYEE_ID) || ')'
FROM
	EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY
	D.DEPARTMENT_ID
ORDER BY
	D.DEPARTMENT_ID ASC
;

-- 125. 부서별 사원의 수를 스칼라쿼리를 이용해 다음과 같이 조회한다. "부서명 (사원의 수)"
SELECT
	D.DEPARTMENT_NAME || ' (' ||
    (
	SELECT
		COUNT(*)
	FROM
		EMPLOYEES E
	WHERE
		E.DEPARTMENT_ID = D.DEPARTMENT_ID
    ) || ')' AS 부서별_사원수
FROM
	DEPARTMENTS D
;

-- 126. 사원의 정보를 다음과 같이 조회한다. "사원번호 번 사원의 이름은 성이름 입니다."
SELECT
	EMPLOYEE_ID || ' 사원의 이름은 ' || LAST_NAME || FIRST_NAME || ' 입니다.'
FROM
	EMPLOYEES
;

-- 127. 사원의 정보를 스칼라쿼리를 이용해 다음과 같이 조회한다. "사원번호 번 사원의 상사명은 상사명 입니다."
SELECT
	E.EMPLOYEE_ID || ' 번 사원의 상사명은 ' ||
    (
	SELECT
		FIRST_NAME || LAST_NAME
	FROM
		EMPLOYEES M
	WHERE
		M.EMPLOYEE_ID = E.MANAGER_ID
    ) || ' 입니다.' AS 부서별_사원수
FROM
	EMPLOYEES E
;

-- 128. 사원의 정보를 조인을 이용해 다음고 같이 조회한다. "사원명 (직무명)"
SELECT
	E.FIRST_NAME || ' ' || '(' || D.DEPARTMENT_NAME || ')'
FROM
	EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
;

-- 129. 사원의 정보를 스칼라쿼리를 이용해 다음과 같이 조회한다. "사원명 (직무명)"
SELECT
	E.FIRST_NAME || E.LAST_NAME || ' (' ||
    (
	SELECT
		J.JOB_TITLE
	FROM
		JOBS J
	WHERE
		J.JOB_ID = E.JOB_ID
    ) || ')' AS 사원명_직무명
FROM
	EMPLOYEES E
;

-- 130. 부서별 월급 차이(최고월급 - 최저월급)가 가장 큰 부서명을 조회한다.
SELECT
	DEPARTMENT_NAME,
	TOTAL_SALARY
FROM
	(
	SELECT
		D.DEPARTMENT_NAME,
		MAX(E.SALARY) - MIN(E.SALARY) AS TOTAL_SALARY
	FROM
		EMPLOYEES E
	INNER JOIN DEPARTMENTS D
ON
		E.DEPARTMENT_ID = D.DEPARTMENT_ID
	GROUP BY
		D.DEPARTMENT_NAME
	ORDER BY
		TOTAL_SALARY DESC)
WHERE
	ROWNUM = 1
	;

-- 131. 부서별 월급 차이(최고월급 - 최저월급)가 가장 큰 부서에서 근무하는 사원들의 직무명을 중복없이 조회한다.
SELECT
	DISTINCT
    J.JOB_TITLE
FROM
	EMPLOYEES E
INNER JOIN DEPARTMENTS D
    ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN JOBS J
    ON
	E.JOB_ID = J.JOB_ID
WHERE
	D.DEPARTMENT_NAME =
    (
	SELECT
		DEPARTMENT_NAME
	FROM
		(
		SELECT
			D.DEPARTMENT_NAME,
			MAX(E.SALARY) - MIN(E.SALARY) AS SALARY_DIFF
		FROM
			EMPLOYEES E
		INNER JOIN DEPARTMENTS D
                    ON
			E.DEPARTMENT_ID = D.DEPARTMENT_ID
		GROUP BY
			D.DEPARTMENT_NAME
		ORDER BY
			SALARY_DIFF DESC
            )
	WHERE
		ROWNUM = 1
    )
;

-- 132. 부서장이 없는 부서명 중 첫 글자가 'C' 로 시작하는 부서명을 조회한다.
SELECT
	DEPARTMENT_ID,
	DEPARTMENT_NAME,
	MANAGER_ID,
	LOCATION_ID
FROM
	DEPARTMENTS
WHERE
	MANAGER_ID IS NULL
	AND DEPARTMENT_NAME LIKE 'C%'
;

-- 133. 부서장이 있는 부서명 중 첫 글자가 'S' 로 시작하는 부서에서 근무중인 사원의 이름과 직무명, 부서명을 조회한다. - 79
SELECT
	E.FIRST_NAME,
	J.JOB_TITLE,
	D.DEPARTMENT_NAME
FROM
	EMPLOYEES E
INNER JOIN JOBS J
ON
	E.JOB_ID = J.JOB_ID
INNER JOIN DEPARTMENTS D
    ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE
	D.DEPARTMENT_NAME LIKE 'S%'
;

-- 134. 지역변호가 1000 ~ 1999 사이인 지역내 부서의 모든 정보를 조회한다.
SELECT
	DEPARTMENT_ID,
	DEPARTMENT_NAME,
	MANAGER_ID,
	LOCATION_ID
FROM
	DEPARTMENTS
WHERE
	LOCATION_ID BETWEEN 1000 AND 1999
;

-- 135. 90 또는 60 또는 100번 부서에서 근무중인 사원의 이름, 성, 부서명을 조회한다. -- 14 ROW
SELECT
	E.FIRST_NAME,
	E.LAST_NAME,
	D.DEPARTMENT_NAME
FROM
	EMPLOYEES E
INNER JOIN DEPARTMENTS D
    ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE
	D.DEPARTMENT_ID IN (90, 60, 100)
;

-- 136. 부서명이 5글자 미만인 부서에서 근무중인 사원의 이름, 부서명을 조회한다.
-- LENGTH : 글자 길이
-- 		DEPARTMENT_NAME, DEPARTMENT_ID : 이 두개도 있어야 값이 나올 수 있음 DEPARTMENTS안에 잇는걸 조회해야하서
SELECT 
	E.FIRST_NAME,
	D.DEPARTMENT_NAME
FROM
	EMPLOYEES E
INNER JOIN (
	SELECT
		DEPARTMENT_NAME,
		DEPARTMENT_ID,
		LENGTH(DEPARTMENT_NAME) AS LENGTH_NAME
	FROM
		DEPARTMENTS) D
    ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE
	LENGTH_NAME < 5
;

-- 137. 국가 아이디가 'C'로 시작하는 국가의 지역을 모두 조회한다.
SELECT
	LOCATION_ID,
	STREET_ADDRESS,
	POSTAL_CODE,
	CITY,
	STATE_PROVINCE,
	COUNTRY_ID
FROM
	LOCATIONS
WHERE
	COUNTRY_ID LIKE 'C%'
	-- C로 시작하고 뒤에 있을 수도 없을 수도 있다.
;

-- 국가명이 'a'로 끝나는 국가의 모든 정보를 조회한다. '%a'
SELECT
	COUNTRY_ID,
	COUNTRY_NAME,
	REGION_ID
FROM
	COUNTRIES
WHERE
	COUNTRY_NAME LIKE '%a'
;

-- 국가명이 'a'로 끝나지 않는 구가의 모든 정보를 조회한다.
SELECT
	COUNTRY_ID,
	COUNTRY_NAME,
	REGION_ID
FROM
	COUNTRIES
WHERE
	COUNTRY_NAME NOT LIKE '%a'
;

-- 138. 국가 아이디의 첫 글자와 국가명의 첫 글자가 다른 모든 국가를 조회한다.
SELECT
	COUNTRY_ID,
	COUNTRY_NAME,
	REGION_ID
FROM
	(
	SELECT
		COUNTRY_ID,
		COUNTRY_NAME,
		REGION_ID,
		SUBSTR(COUNTRY_ID, 1, 1) AS COUNTRY_ID_FIRST,
		SUBSTR(COUNTRY_NAME, 1, 1) AS COUNTRY_NAME_FIRST
	FROM
		COUNTRIES)
WHERE
	COUNTRY_ID_FIRST != COUNTRY_NAME_FIRST
;

-- 이렇게도 가능하다.
SELECT
	COUNTRY_ID,
	COUNTRY_NAME,
	REGION_ID
FROM
	(
	SELECT
		COUNTRY_ID,
		COUNTRY_NAME,
		REGION_ID,
		SUBSTR(COUNTRY_ID, 1, 1) AS COUNTRY_ID_FIRST,
		--SUBSTR(COUNTRY_NAME, 1, 1) AS COUNTRY_NAME_FIRST
	FROM
		COUNTRIES)
WHERE
	COUNTRY_ID_FIRST != SUBSTR(COUNTRY_NAME, 1, 1)
;

-- 139. 사원 모든 정보 중 이메일만 모두 소문자로 변경하여 조회한다.
SELECT
	EMPLOYEE_ID,
	FIRST_NAME,
	LAST_NAME,
	LOWER(EMAIL),
	PHONE_NUMBER,
	HIRE_DATE,
	JOB_ID,
	SALARY,
	MANAGER_ID,
	DEPARTMENT_ID
FROM
	EMPLOYEES
;

-- 140. 사원의 월급을 TRUNC(소수점 버림) 함수를 사용해 100 단위는 버린채 다음과 같이 조회한다. 예> 3700 -> 3000, 12700 -> 12000
SELECT
	SALARY,
	TRUNC(SALARY, -4) AS SALARY_TRUNC
FROM
	EMPLOYEES
;

-- 141. 100단위를 버린 사원의 월급 별 사원의 수를 조회한다.
SELECT
	COUNT(*),
	SALARY_TRUNC
FROM
	(
	SELECT
		TRUNC(SALARY, -3) AS SALARY_TRUNC
	FROM
		EMPLOYEES)
GROUP BY
	SALARY_TRUNC
;

SELECT
	COUNT(*),
	SALARY_TRUNC
FROM
	(
	SELECT
		TRUNC(SALARY / 1000)* 1000 AS SALARY_TRUNC
	FROM
		EMPLOYEES)
GROUP BY
	SALARY_TRUNC
;

-- 142. 현재 시간으로부터 20년 전 보다 일찍 입사한 사원의 모든 정보를 조회한다.
-- 20년 전은 2006년 2월 12일
SELECT                 
	EMPLOYEE_ID,       
	FIRST_NAME,        
	LAST_NAME,         
	EMAIL,             
	PHONE_NUMBER,      
	HIRE_DATE,         
	JOB_ID,            
	SALARY,            
	COMMISSION_PCT,    
	MANAGER_ID,        
	DEPARTMENT_ID
FROM                   
	EMPLOYEES
WHERE
	HIRE_DATE < ADD_MONTHS(SYSDATE, -20 * 12)
;

-- 143. 부서번호별 현재 시간으로부터 15년 전 보다 일찍 입사한 사원의 수를 조회한다. - 12
SELECT
	DEPARTMENT_ID,
	COUNT(EMPLOYEE_ID)
FROM
	EMPLOYEES
WHERE
	HIRE_DATE < ADD_MONTHS(SYSDATE, -15 * 12)
GROUP BY
	DEPARTMENT_ID
;

-- 144. 부서명, 직무명 별 평균 월급을 조회한다. -19
SELECT
	D.DEPARTMENT_NAME,
	J.JOB_TITLE,
	AVG(E.SALARY)
FROM
	EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN JOBS J
ON
	E.JOB_ID = J.JOB_ID
GROUP BY
	D.DEPARTMENT_NAME,
	J.JOB_TITLE
;

-- 145. 도시명, 직무명 별 사원의 수를 조회한다. -19
SELECT
	L.CITY,
	J.JOB_TITLE,
	COUNT(E.EMPLOYEE_ID)
FROM
	EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN LOCATIONS L
ON
	D.LOCATION_ID = L.LOCATION_ID
INNER JOIN JOBS J
ON
	E.JOB_ID = J.JOB_ID
GROUP BY
	L.CITY,
	J.JOB_TITLE
;

-- 146. 부서명, 직무명 별 평균 월급 중 가장 작은 평균월급을 받는 부서명, 직무명을 조회한다.
SELECT
	DEPARTMENT_NAME,
	JOB_TITLE
FROM
	(
	SELECT
		D.DEPARTMENT_NAME,
		J.JOB_TITLE,
		AVG(E.SALARY) AS AVG_SALARY
	FROM
		EMPLOYEES E
	INNER JOIN DEPARTMENTS D
            ON
		E.DEPARTMENT_ID = D.DEPARTMENT_ID
	INNER JOIN JOBS J
            ON
		E.JOB_ID = J.JOB_ID
	GROUP BY
		D.DEPARTMENT_NAME,
		J.JOB_TITLE
	ORDER BY
		AVG_SALARY ASC
    )
WHERE
		ROWNUM = 1
;

-- 147. 102번 직원의 모든 부하직원의 수를 조회한다.
-- WHERE가 먼저 나오고 그다음이 START 가 나와야한다.
SELECT
	COUNT(*)
FROM
	EMPLOYEES
WHERE
	EMPLOYEE_ID IS NOT NULL
START WITH
	EMPLOYEE_ID = 102
CONNECT BY
	PRIOR EMPLOYEE_ID = MANAGER_ID
;

-- 148. 113번 직원의 모든 부하직원의 수를 조회한다.
SELECT
	COUNT(*)
FROM
	EMPLOYEES
WHERE
	EMPLOYEE_ID IS NOT NULL
START WITH
	EMPLOYEE_ID = 113
CONNECT BY
	PRIOR EMPLOYEE_ID = MANAGER_ID
;

-- 149. 부하직원이 없는 사원의 모든 정보를 조회한다. - 89
SELECT
	EMPLOYEE_ID,
	FIRST_NAME,
	LAST_NAME,
	EMAIL,
	PHONE_NUMBER,
	HIRE_DATE,
	JOB_ID,
	SALARY,
	COMMISSION_PCT,
	MANAGER_ID,
	DEPARTMENT_ID
FROM
	EMPLOYEES
WHERE
	EMPLOYEE_ID NOT IN (
	SELECT
		MANAGER_ID
	FROM
		EMPLOYEES
	WHERE
		MANAGER_ID IS NOT NULL
    )
;

-- 150. 사원번호가 100번인 사원의 사원번호, 이름과 사원번호로 내림차순 정렬된 사원의 사원번호, 이름 조회한다.
/*조회 예
--------------------
100    Steven
206    William
205    Shelley
204    Hermann
203    Susan
202    Pat
201    Michael
200    Jennifer
199    Douglas
198    Donald
197    Kevin
196    Alana
...
*/
-- 페이징을 해서 INLINE VIEW를 해준다.
-- 똑같은 타입으로 흘러가야 할 수 있다. 
-- 1번과 2번의 타입이 일치해야 할 수 있다. 숫자, 문자 혹은 문자, 순자 등 같아야한다.
-- 성능 계선을 위해서 사용
SELECT
	-- 여기 1번
	EMPLOYEE_ID,
	FIRST_NAME,
	LAST_NAME
FROM
	EMPLOYEES
WHERE
	EMPLOYEE_ID = 100
UNION ALL
-- 위랑 아래의 코드를 하나로 만들어라
SELECT
	-- 여기 2번
	EMPLOYEE_ID,
	FIRST_NAME,
	''
FROM
	(
	SELECT 
		EMPLOYEE_ID,
		FIRST_NAME
	FROM
		EMPLOYEES
	WHERE
		EMPLOYEE_ID NOT IN 100
	ORDER BY
		EMPLOYEE_ID DESC)
;

-- 151. 모든 사원들의 사원번호, 부서번호, 부서명을 조회한다. 근무중인 부서가 없다면 null로 표시한다.
SELECT
	E.EMPLOYEE_ID,
	D.DEPARTMENT_ID,
	D.DEPARTMENT_NAME
FROM
	EMPLOYEES E
LEFT OUTER JOIN DEPARTMENTS D
ON
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY
	E.EMPLOYEE_ID ASC
;

-- 152. 부서에서 근무하는 모든 사원들의 이름, 부서번호, 부서명을 조회한다. 근무중인 사원이 없다면 null로 표시한다.
SELECT
	E.FIRST_NAME,
	E.EMPLOYEE_ID,
	D.DEPARTMENT_ID,
	D.DEPARTMENT_NAME
FROM
	DEPARTMENTS D
LEFT OUTER JOIN EMPLOYEES E
ON
	D.DEPARTMENT_ID = E.DEPARTMENT_ID
ORDER BY
	E.EMPLOYEE_ID ASC
;

SELECT
	E.FIRST_NAME,
	E.EMPLOYEE_ID,
	D.DEPARTMENT_ID,
	D.DEPARTMENT_NAME
FROM
	EMPLOYEES E
RIGHT OUTER JOIN DEPARTMENTS D
ON
	D.DEPARTMENT_ID = E.DEPARTMENT_ID
ORDER BY
	E.EMPLOYEE_ID ASC
;

-- 153. 모든 부서의 부서장들의 사원번호, 이름, 성, 부서명을 조회한다. 부서장이 없다면 null로 표시한다.
SELECT
	E.EMPLOYEE_ID,
	E.FIRST_NAME,
	E.LAST_NAME,
	D.DEPARTMENT_ID,
	D.DEPARTMENT_NAME,
	D.MANAGER_ID
FROM
	DEPARTMENTS D
LEFT OUTER JOIN EMPLOYEES E
ON
	D.DEPARTMENT_ID = E.DEPARTMENT_ID
ORDER BY
	E.EMPLOYEE_ID ASC
;

-- 154. 모든 지역에 존재하는 부서들의 도시명, 부서명을 조회한다. 부서가 없다면 null로 표시한다.
SELECT
	L.CITY,
	D.DEPARTMENT_NAME
FROM
	LOCATIONS L
LEFT OUTER JOIN DEPARTMENTS D
ON
	L.LOCATION_ID = D.LOCATION_ID
;

-- 155. 모든 국가에 존재하는 도시명, 부서명을 조회한다. 도시 또는 부서가 없다면 null로 표시한다.
SELECT
	D.DEPARTMENT_NAME,
	L.CITY
FROM
	COUNTRIES C
LEFT JOIN LOCATIONS L
    ON
	C.COUNTRY_ID = L.COUNTRY_ID
LEFT JOIN DEPARTMENTS D
    ON
	L.LOCATION_ID = D.LOCATION_ID
;

SELECT
	L.DEPARTMENT_NAME,
	L.CITY
FROM
	COUNTRIES C
LEFT JOIN (
	SELECT
		*
	FROM
		LOCATIONS L
	LEFT JOIN DEPARTMENTS D
    ON
		L.LOCATION_ID = D.LOCATION_ID) L
ON
	C.COUNTRY_ID = L.COUNTRY_ID
;

-- 156. 모든 부서별로 근무하는 사원의 수를 조회한다. 근무중인 사원이 없다면 0으로 표시한다.
SELECT
	D.DEPARTMENT_NAME,
	COUNT(E.EMPLOYEE_ID)
FROM
	DEPARTMENTS D
LEFT OUTER JOIN EMPLOYEES E
ON
	D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY
	D.DEPARTMENT_NAME
ORDER BY
	D.DEPARTMENT_NAME ASC
;

-- 157. 모든 지역별로 근무하는 사원의 수를 조회한다. 근무중인 사원이 없아면 0으로 표시한다.
SELECT
	L.LOCATION_ID,
	COUNT(E.EMPLOYEE_ID)
FROM
	LOCATIONS L
LEFT JOIN DEPARTMENTS D
    ON
	L.LOCATION_ID = D.LOCATION_ID
LEFT OUTER JOIN EMPLOYEES E
ON
	D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY
	L.LOCATION_ID
ORDER BY
	L.LOCATION_ID ASC
;

-- 158. 모든 국가에 존재하는 부서의 수를 조회한다. 부서가 없다면 0으로 표시한다.
SELECT
	C.COUNTRY_ID,
	COUNT(D.DEPARTMENT_ID)
FROM
	COUNTRIES C
LEFT JOIN LOCATIONS L
    ON
	C.COUNTRY_ID = L.COUNTRY_ID
LEFT JOIN DEPARTMENTS D
    ON
	L.LOCATION_ID = D.LOCATION_ID
GROUP BY
	C.COUNTRY_ID
ORDER BY
	C.COUNTRY_ID ASC
;

